// 500 Unique Review Templates (100 per rating 1 to 5)
// Rating 3, 4, and 5 are crafted as the BEST high-converting, positive, and authentic reviews.
// All templates support dynamic `{name}` replacement.

export const REVIEW_TEMPLATES: Record<number, string[]> = {
  5: [
    // 1-10: Ambiance & Aesthetics
    "Absolutely blown away by the stunning ambiance at {name}! The lighting, aesthetics, and cozy seating make it the best hangout spot.",
    "The vibe at {name} is unmatched! Beautiful interior decor, great background music, and a very relaxing atmosphere.",
    "{name} is an aesthetic paradise! Every corner is Instagram-worthy, and the overall vibe is super chill.",
    "Loved the rooftop and interior setup at {name}. Perfect lighting, comfortable seating, and wonderful music playlist.",
    "The mood and decor at {name} set the bar really high. Easily one of the most beautiful cafes in town!",
    "Had the most relaxing evening at {name}! The warm golden ambience and soothing music make it a 10/10 experience.",
    "From the entrance to the seating, {name} oozes charm and elegance. A truly upscale cafe experience!",
    "{name} has such a warm, inviting energy. The open-air vibe combined with classy interiors made our visit unforgettable.",
    "A gorgeous place with incredible attention to detail! {name} is definitely my new favorite spot to unwind.",
    "The atmosphere at {name} is pure magic. Great crowd, fantastic decor, and an energetic yet peaceful vibe.",

    // 11-20: Food Taste & Quality
    "The food at {name} was nothing short of perfection! Every single dish was bursting with fresh, authentic flavors.",
    "Incredible culinary experience at {name}! The pasta and wood-fired pizza were cooked to absolute perfection.",
    "Hands down the tastiest cafe food I've had in a long time! {name} nailed every dish we ordered today.",
    "Delicious food with five-star presentation! {name} truly takes pride in the quality of ingredients they use.",
    "The flavors at {name} are extraordinary! Freshly prepared, well-seasoned, and served piping hot. Truly impressed!",
    "Every bite at {name} was a delight! Whatever you do, don't miss out on their signature appetizers and main courses.",
    "Top-notch gastronomic experience at {name}! The chef deserves huge praise for crafting such delicious recipes.",
    "Food lovers, rejoice! {name} delivers gourmet quality food in a relaxed, comfortable cafe setting. Loved it!",
    "The gourmet platters at {name} exceeded all expectations. Fresh ingredients, delightful sauces, and great aroma.",
    "Sensational food! Everything from the crispy starters to the flavorful mains at {name} was top tier.",

    // 21-30: Beverages, Coffees & Drinks
    "The coffee at {name} is artisan quality! Perfectly brewed, rich crema, and incredible aroma. Best brew in town!",
    "Had the most refreshing mocktails at {name}! Perfectly balanced sweetness, beautifully presented, and super chilled.",
    "If you love specialty coffee, {name} is the place to be! Their cold brews and lattes are second to none.",
    "The beverage menu at {name} is phenomenal! Great variety of coolers, shakes, and premium artisanal teas.",
    "Tried their signature coolers and handcrafted coffee at {name} - both were utterly refreshing and perfectly blended.",
    "Kudos to the baristas at {name}! My cappuccino was velvety smooth and had gorgeous latte art on top.",
    "The shakes and smoothies at {name} are thick, rich, and made with genuine quality ingredients. 5 stars!",
    "Such creative beverages at {name}! Every drink looks stunning and tastes even better. Highly recommended!",
    "The iced latte and fruit coolers at {name} were pure bliss on a warm afternoon. Can't wait to order again!",
    "A haven for coffee lovers! {name} brews some of the smoothest, most flavorful coffee you will find anywhere.",

    // 31-40: Hospitality & Service
    "The hospitality at {name} is world-class! The team was so polite, attentive, and made us feel truly welcomed.",
    "Outstanding customer service at {name}! The staff greeted us with genuine smiles and offered great recommendations.",
    "Remarkable staff at {name}! They took care of our custom dietary requests effortlessly and checked in regularly.",
    "Service with a smile! The servers at {name} are courteous, efficient, and genuinely passionate about hospitality.",
    "Felt like royalty dining at {name}! The attentiveness and professionalism of the staff were second to none.",
    "The staff at {name} went above and beyond to make our dining experience comfortable. Exceptional service!",
    "Prompt, polite, and thoroughly professional staff at {name}. They made our family dinner smooth and delightful.",
    "Huge shoutout to the serving team at {name}! Quick on their feet and always ready with helpful suggestions.",
    "Warm hospitality and swift service! {name} knows exactly how to treat its guests right from start to finish.",
    "The management and staff at {name} are doing a phenomenal job. Courteous, prompt, and very accommodating!",

    // 41-50: Celebrations & Group Outings
    "Celebrated my birthday at {name} and it was unforgettable! The staff helped us organize everything seamlessly.",
    "The best venue for celebrations! We hosted a friends' reunion at {name} and everyone had a blast.",
    "Had a group party at {name} and the vibes were electric! Plenty of space, great music, and delicious sharing platters.",
    "Celebrated our anniversary at {name} and it couldn't have been more romantic. Thank you for the special hospitality!",
    "Great place for hosting private get-togethers! {name} managed our large group order with total efficiency and grace.",
    "Our family get-together at {name} was a massive hit! Kids and elders alike thoroughly enjoyed the food and setting.",
    "Hosted an office celebration at {name} - prompt service, spacious seating, and delicious finger food throughout.",
    "If you're planning any celebration or weekend party, {name} is the top choice. The atmosphere is vibrant and joyful!",
    "Unforgettable evening celebrating with friends at {name}! The music, food, and drinks kept the spirits high all night.",
    "Special occasions deserve special places, and {name} made our milestone celebration truly magical!",

    // 51-60: Date Nights & Couples
    "The perfect date night destination! {name} offers cozy corners, romantic candlelit vibes, and delicious cuisine.",
    "Took my partner to {name} for a romantic dinner, and we both fell in love with the serene and intimate setting.",
    "Romantic music, dim aesthetic lighting, and delectable dishes make {name} the ultimate date spot in the city.",
    "Such a romantic and charming ambiance at {name}! Ideal for couples looking for a cozy, upscale dining experience.",
    "An intimate culinary escape! {name} set the mood perfectly for our date night with soft jazz and warm hospitality.",
    "If you want to impress your date, take them to {name}. The food, the drinks, and the view are unbeatable.",
    "Loved the private, cozy vibe at {name}. A beautiful retreat away from the city hustle for couples.",
    "Everything about {name} screams elegance and romance. Delicious food paired with a dreamy, relaxing vibe.",
    "Our romantic dinner at {name} was straight out of a movie! Quiet corners, stellar food, and sweet background music.",
    "Can't think of a better place for a couple's evening than {name}. Absolute perfection in every department!",

    // 61-70: Work & Casual Hangouts
    "Great place to work remotely or read a book! {name} has comfortable seating, quiet spots, and great coffee.",
    "Spent a productive afternoon working at {name}. High-speed vibes, tasty snacks, and endless cups of great coffee.",
    "Super relaxed cafe! {name} is the ideal spot to catch up with colleagues or just spend some peaceful me-time.",
    "Comfortable chairs, calm ambient music, and great lattes make {name} a brilliant workspace during daytime.",
    "Whether you're working on your laptop or chilling with buddies, {name} provides the most welcoming environment.",
    "Peaceful, chic, and comfortable. {name} is the ultimate daytime retreat for creative minds and remote workers.",
    "A cozy sanctuary! Spent three hours at {name} reading and sipping on their special brews. Pure relaxation.",
    "{name} has the perfect balance of lively energy and peaceful seating. Ideal for casual afternoon meetings.",
    "My favorite neighborhood cafe! {name} is always clean, welcoming, and perfect for getting work done over coffee.",
    "Great Wi-Fi, comfortable booths, and delicious coffee - {name} is an absolute gem for casual day-outs.",

    // 71-80: Desserts & Bakery
    "The desserts at {name} are heavenly! Rich chocolate indulgence, perfectly balanced sweetness, and exquisite texture.",
    "Save room for dessert when visiting {name}! Their cheesecake and artisan pastries are truly world-class.",
    "Sweet tooth heaven! The warm brownie and artisanal desserts at {name} melted right in our mouths.",
    "The bakery items at {name} taste like they came straight out of a Parisian patisserie. Utterly divine!",
    "Had the most decadent dessert at {name}! Premium chocolate, fresh berry coulis, and stunning visual presentation.",
    "Do yourself a favor and order their desserts at {name}. Freshly baked, perfectly moist, and full of rich flavors.",
    "The tiramisu at {name} is hands down the best in town. Light, authentic, and perfectly balanced with coffee notes.",
    "Every dessert at {name} looks like a piece of art and tastes even better. Simply unmatched sweet treats!",
    "A sweet lover's dream! The warm waffle and ice cream pairing at {name} was the perfect end to our feast.",
    "Dessert perfection! {name} serves freshly crafted bakery delights that leave you craving more.",

    // 81-90: Speed & Consistency
    "Always consistent and always fantastic! This is my fourth visit to {name} and every experience has been 5 stars.",
    "Impressive kitchen speed at {name}! Our food arrived piping hot and fresh within minutes of placing the order.",
    "Consistently outstanding! No matter what time of day you visit, {name} always delivers top quality and warmth.",
    "Zero delays and flawless execution at {name}. The food arrived together, hot, and tasting extraordinary.",
    "Quick table turnaround and seamless ordering. {name} runs like a well-oiled machine without cutting corners.",
    "Consistency is key, and {name} never fails to impress. Great taste, swift service, and immaculate cleanliness.",
    "Food arrived remarkably fast without compromising an ounce of quality or presentation at {name}. Superb!",
    "I've been a regular customer at {name} for months now, and the quality has remained stellar on every single trip.",
    "Fast, fresh, and exceptionally delicious! {name} handles busy dinner rushes with effortless professionalism.",
    "From greeting to bill settlement, the service at {name} was swift, efficient, and thoroughly pleasant.",

    // 91-100: Overall Stellar Impression
    "{name} is an absolute gem! Superb food, gorgeous decor, and unforgettable hospitality. Highly recommended to all!",
    "Without a doubt, {name} is one of the premier cafes in the region. Everything they do, they do with excellence.",
    "An extraordinary dining destination! {name} checks all the right boxes: taste, vibe, hygiene, and service.",
    "Can't say enough good things about {name}! Five stars aren't enough to capture how wonderful our experience was.",
    "A must-visit spot for both locals and travelers! {name} is setting a new benchmark for cafe culture.",
    "Everything about {name} exceeded our wildest expectations. We are already planning our next visit!",
    "Absolute perfection! {name} has earned a lifelong fan in me. Will be recommending this place to all my friends.",
    "Pure elegance and culinary delight! {name} delivers an all-round five-star experience that you won't forget.",
    "A truly sensational cafe! {name} combines culinary artistry with warm vibes. Don't think twice, just visit!",
    "Top tier in every single category! {name} is a shining star in the city's food scene. 10/10 recommendation!"
  ],

  4: [
    // 1-10: Great Food & Fresh Flavors
    "Really enjoyed our visit to {name}! The food was mouth-watering, freshly prepared, and full of authentic flavor.",
    "Delicious meal at {name}! Everything tasted wonderful and fresh. The presentation and seasonings were spot on.",
    "Great flavors at {name}! The pizza and appetizers were superb, and the staff was extremely warm and polite.",
    "Had a lovely lunch at {name}. The pasta was authentic and rich, paired with fantastic refreshing beverages.",
    "The taste of the food at {name} was top quality! Fresh ingredients and lovely plating made it very special.",
    "Wonderful flavors at {name}! Starters arrived fresh and crispy, while the mains were hearty and flavorful.",
    "Food was exceptional at {name}! Truly enjoyed the gourmet burgers, seasoned fries, and creamy pasta.",
    "Tasty and wholesome food at {name}! The recipes are authentic and the flavors lingered long after the meal.",
    "Loved the recipes at {name}! High quality ingredients and great taste across every dish we ordered.",
    "Really good culinary standards at {name}. Delicious food served with care and great attention to detail."
  ,
    // 11-20: Lovely Ambiance & Aesthetics
    "The ambiance at {name} is gorgeous! Beautiful lights, stylish decor, and a wonderfully positive vibe.",
    "Super cozy vibe at {name}! The seating arrangement and aesthetic decor make it a truly charming venue.",
    "Loved the aesthetic interiors of {name}! Chic design, comfortable furniture, and a very relaxing environment.",
    "Very stylish cafe with pleasant decor! {name} has created a wonderful atmosphere for friends and families.",
    "{name} has such a charming setup. Great background music, elegant lights, and comfortable corners throughout.",
    "Great background music and beautiful seating at {name}. The whole experience was smooth and delightful.",
    "Lovely place to hang out with friends! {name} offers wonderful energy, great aesthetics, and comfortable booths.",
    "The rooftop atmosphere at {name} is fantastic. Breezy open-air seating combined with lovely evening lights.",
    "Really charming interior aesthetics at {name}. The visual appeal makes your cafe visit feel extra special.",
    "Warm, rustic, and pleasant ambiance at {name}! A fantastic destination for weekend chill and casual dining."
  ,
    // 21-30: Delicious Coffee & Beverages
    "Great coffee at {name}! The brew was strong, aromatic, and had rich velvety foam. Highly recommended!",
    "Loved the iced teas and smoothies at {name}! Refreshing, perfectly balanced, and served nice and chilled.",
    "Coffee lovers will appreciate {name}! Great cappuccino, rich latte, and wonderful specialty cold brews.",
    "Refreshing mocktails and tasty finger food at {name}. The drinks were presented beautifully and tasted crisp.",
    "Had a great cold brew at {name}! Perfect temperature, smooth finish, and wonderful flavor profile.",
    "The beverage menu at {name} has plenty of variety. Our drinks were delicious, vibrant, and very satisfying.",
    "Great artisanal brews at {name}! The coffee was on point and the barista clearly knows their craft well.",
    "Loved the fruit coolers at {name}! Perfect balance of sweet and tangy flavors. Will definitely order again.",
    "Very good shakes and frappes at {name}! Rich texture, great chocolate flavor, and premium toppings.",
    "The hot chocolate and cappuccinos at {name} were comforting and rich. Lovely drink options on the menu."
  ,
    // 31-40: Courteous Staff & Service
    "Staff at {name} was very courteous and accommodating! Always attentive and made us feel right at home.",
    "Pleasant hospitality at {name}! The servers were friendly, polite, and patient with our customized requests.",
    "The team at {name} is warm and polite. Hard-working staff doing a wonderful job ensuring guest comfort.",
    "Good service at {name}! Staff gave great food recommendations that we thoroughly enjoyed. Very polite crew.",
    "Friendly smiles from the staff at {name}. They checked in on our table and made sure everything was fine.",
    "Helpful and well-mannered staff at {name}. They made sure our glasses were full and plates were cleared promptly.",
    "Staff at {name} greeted us warmly at the door. Prompt service, respectful attitudes, and great manners.",
    "Courteous team members at {name}. They explained the signature dishes nicely and served with enthusiasm.",
    "Prompt greeting and good manners from the crew at {name}. Kept the dining experience enjoyable throughout.",
    "The hospitality at {name} is definitely commendable. Friendly staff that genuinely cares about your visit."
  ,
    // 41-50: Pleasant Vibe & Music
    "Good music playlist at {name}! Set a lovely mood for our dinner. Upbeat, modern, and very enjoyable.",
    "Enjoyed the playlist and vibe at {name}. Cozy lighting and great acoustics make for a very relaxing hangout.",
    "The mood lighting at {name} creates an intimate setting. Wonderful soundtrack that complements the evening.",
    "Nice tunes playing in the background at {name}. Comfortable couches and relaxed seating arrangements.",
    "The vibe at {name} is lively yet comforting. Perfect place to unwind with close friends after a busy week.",
    "Pleasant background melodies at {name} that set a great tone without overpowering conversation.",
    "Loved the evening lighting and chill beats at {name}. A great spot to unwind and enjoy good company.",
    "Fun and upbeat environment at {name}. Clean tables, cozy corners, and good music make it a wonderful visit.",
    "Chill vibes throughout {name}! Perfect background soundtrack for chilling with buddies over snacks.",
    "The interior acoustics and music choices at {name} were enjoyable. Felt relaxed from the moment we walked in."
  ,
    // 51-60: Value & Quality
    "Good portion sizes and fair pricing at {name}. The food was tasty, fulfilling, and gave great value for money.",
    "Reasonably priced menu at {name} given the upscale ambiance, fresh ingredients, and prime location.",
    "Generous servings and flavorful seasoning at {name}! Left the cafe feeling completely full and happy.",
    "Good value for an upscale cafe experience at {name}. Quality was evident in every single dish served.",
    "Fair pricing structure at {name}. Tasty food and quality handcrafted beverages without exorbitant bills.",
    "Decent portion sizes and great seasoning at {name}. Loved the balance of taste, quantity, and presentation.",
    "Price matches the high quality and aesthetics at {name}. Everything tasted fresh and well-prepared.",
    "Satisfying meal portions at {name}! Shared platters with friends and everyone was thoroughly satisfied.",
    "The combo meals and platters at {name} offer good value. Tasty options for casual dining with groups.",
    "Great balance of quality and pricing at {name}. Worth visiting for both casual coffee and full meals."
  ,
    // 61-70: Cleanliness & Comfort
    "Clean and hygienic setup at {name}! Sanitized tables, clean cutlery, and a very fresh atmosphere throughout.",
    "Great spot for hanging out with friends! {name} has spacious seating, clean washrooms, and tidy tables.",
    "Impressed with the hygiene standards at {name}. Everything looked clean, tidy, and well-maintained.",
    "A dependable place to meet friends! {name} is comfortable, tidy, and serves delicious quick bites.",
    "Comfortable seating and well-maintained interiors at {name}. A pleasant cafe to spend quality time.",
    "Spotless dining area and quick table cleanup at {name}. Great to see a cafe that takes hygiene seriously.",
    "Nice and airy setup at {name}. Tables are well-spaced so you enjoy privacy and comfort during your meal.",
    "Great cafe to lounge around on a lazy afternoon. {name} has friendly staff and a clean, relaxed environment.",
    "Neat and organized cafe! {name} delivers on cleanliness, comfort, and enjoyable cafe bites every time.",
    "Good hygiene, tidy tables, and comfortable booths at {name}. Definitely one of the cleaner cafes around."
  ,
    // 71-80: Varied Menu & Plating
    "Extensive menu with lots of appetizing options at {name}! Great variety of continental and fusion dishes.",
    "Food presentation at {name} is lovely! Very photogenic plating and delicious taste to back it up.",
    "Creative menu at {name}! Good variety of starters, mains, and desserts. We enjoyed our selection thoroughly.",
    "Nicely curated food options at {name}. The presentation of starters was appetizing and colorful.",
    "Appreciated the diverse options on {name}'s menu. Something for everyone, from light bites to hearty feasts.",
    "The platters at {name} looked stunning when they arrived at our table. Great flavors to match the visual appeal.",
    "Impressive menu selection at {name}! Tried three new dishes today and each had a unique, pleasant flavor profile.",
    "Great variety of vegetarian and non-vegetarian choices at {name}. Plating was neat and appetite-inducing.",
    "Good culinary choices on the menu at {name}. The chef clearly puts thought into presentation and garnishing.",
    "Well-designed menu with clear descriptions at {name}. The food looked just as good as pictured."
  ,
    // 81-90: Overall Satisfaction
    "Overall a very positive experience at {name}! Delicious food, nice ambiance, and prompt service throughout.",
    "Had an enjoyable time at {name}. Great food, friendly staff, and a lovely ambient atmosphere.",
    "Solid cafe experience at {name}! Great for casual meetups, dates, or family tea time. Will visit again.",
    "Enjoyed the dining experience at {name}. The staff is polite, food is tasty, and the location is convenient.",
    "A very good cafe that gets everything right! {name} has become our favorite spot for casual evening snacks.",
    "Very pleased with our evening at {name}. High quality food, delicious coffee, and commendable hospitality.",
    "Good food, good vibes, and good company at {name}. A reliable place for an enjoyable meal.",
    "Comfortable ambiance and flavorful food make {name} well worth a visit. Happy with the overall service.",
    "Had a wonderful time at {name}! Will gladly bring more friends along on our next visit.",
    "Wonderful performance by {name}. Well managed, tasty dishes, and lovely ambient atmosphere throughout."
  ,
    // 91-100: Warm Recommendations
    "Would definitely recommend {name} to anyone looking for good food and a trendy vibe in the area!",
    "Great addition to the cafe scene! {name} delivers consistent quality and a warm welcoming atmosphere.",
    "A solid choice for evening coffee or dinner! {name} impressed us with its flavors and courteous staff.",
    "Happy to recommend {name}! A lovely venue with great food and a relaxed, contemporary vibe.",
    "Definitely worth checking out! {name} offers good food, cozy seating, and a warm neighborhood feel.",
    "Recommended for anyone who enjoys good food in a trendy setting. {name} does not disappoint.",
    "A very satisfying visit to {name}! I will be returning soon to explore more of their signature menu items.",
    "If you're in the neighborhood, {name} is a reliable choice for delicious snacks and refreshing drinks.",
    "Thumbs up to {name}! Great ambiance, friendly staff, and tasty dishes that leave you satisfied.",
    "Really good experience at {name}. Top-notch food, warm people, and a vibe that makes you want to return!"
  ],

  3: [
    // 1-10: Friendly Vibe & Hangout
    "Had a really pleasant time at {name}! The ambience is warm, staff is courteous, and the food was very tasty.",
    "Loved the calm and cozy atmosphere at {name}. Great spot to enjoy good food and relax with friends.",
    "Good food and lovely music at {name}! The pasta was delicious and the mocktails were very refreshing.",
    "Really liked the vibe at {name}. The seating is comfortable and the staff is very polite and attentive.",
    "A delightful cafe experience at {name}! Fresh food, good coffee, and a very welcoming environment.",
    "{name} has such a charming and relaxed setting. Perfect place for casual meetups and delicious bites.",
    "Enjoyed every bit of our visit to {name}. The starters were flavorful and served piping hot!",
    "Very nice cafe with great hospitality! The team at {name} made sure we had a comfortable time.",
    "Loved the aesthetics and cozy corners at {name}. Food was tasty and coffee was brewed just right.",
    "Such a pleasant place to unwind! {name} offers good food, soothing music, and wonderful service."
  ,
    // 11-20: Tasty Snacks & Bites
    "The pizza and garlic bread at {name} were delicious! Fresh ingredients and great crust. Enjoyed it!",
    "Tasty snacks and great drinks at {name}. The sandwiches were freshly grilled and very satisfying.",
    "Really good culinary choices at {name}. Everything we ordered was fresh, flavorful, and nicely presented.",
    "Loved the crispy starters at {name}! Perfect seasoning and generous dips. Will definitely order again.",
    "A wonderful food experience at {name}! The burger was juicy and the fries were golden and crisp.",
    "Good food that hits the spot! {name} serves fresh, appetizing dishes that make you want to come back.",
    "The pasta at {name} was creamy, flavorful, and cooked to perfection. Loved the overall taste!",
    "Really enjoyed the finger food and platters at {name}. Great quality and very fulfilling meal.",
    "The chef at {name} knows how to balance flavors nicely. Every dish on our table was enjoyable.",
    "Fresh, piping hot food with great taste! {name} delivers a very satisfying cafe dining experience."
  ,
    // 21-30: Good Coffee & Beverages
    "The cold coffee at {name} is simply fantastic! Rich, creamy, and served at the perfect chill.",
    "Loved the iced teas and fresh coolers at {name}. Very refreshing drinks to pair with evening snacks.",
    "A great spot for coffee lovers! {name} serves aromatic brews that brighten up your day instantly.",
    "The beverage menu at {name} is impressive. Had a lovely fruit smoothie that was naturally sweet and thick.",
    "Superb hot chocolate and lattes at {name}! So comforting and rich in flavor. Highly enjoyed it.",
    "The drinks at {name} are beautifully crafted and taste so refreshing. Perfect for an afternoon hangout.",
    "Loved their signature coolers at {name}. Chilled, zesty, and perfect for beating the heat with friends.",
    "Great coffee and cozy seating make {name} a wonderful place to sit and chat for hours.",
    "The shakes at {name} are thick, delicious, and made with top quality ingredients. Very happy!",
    "Refreshing drinks and great hospitality at {name}. The mint mojito was exceptionally crisp and tasty."
  ,
    // 31-40: Cozy Seating & Ambience
    "Such a cozy and welcoming vibe at {name}! The lighting and decor create a very relaxing mood.",
    "Comfortable seating and beautiful decor at {name}. A great place to chill, read, or work peacefully.",
    "Loved the aesthetic interior of {name}! Plenty of photo spots and the music playlist was great.",
    "{name} has a lovely peaceful environment. You can sit comfortably without feeling rushed at all.",
    "The decor at {name} is stylish and modern. Felt very relaxed the moment we walked through the doors.",
    "Great background music that complements conversation at {name}. Comfortable chairs and clean tables.",
    "A hidden gem for casual evenings! {name} offers a charming ambiance paired with delicious food.",
    "Loved the open, airy feel and tasteful lighting at {name}. Makes your cafe visit feel extra special.",
    "Warm, inviting, and wonderfully decorated! {name} is a great place to spend quality time with loved ones.",
    "The vibe at {name} puts you at ease right away. Pleasant interiors and a very peaceful crowd."
  ,
    // 41-50: Courteous Staff
    "The staff at {name} was very courteous and accommodating. They served us with genuine smiles!",
    "Prompt service and well-mannered staff at {name}. They made sure our glasses were always filled.",
    "Helpful team members at {name} who gave us great dish recommendations. Very pleasant experience!",
    "The hospitality at {name} is truly commendable. Attentive without being intrusive. Good job!",
    "Friendly faces and quick service at {name}! The staff was very polite and made us feel welcome.",
    "Appreciated the fast service and warm behavior of the crew at {name}. Everything went smoothly.",
    "Staff at {name} was very patient while taking our customized orders. Great customer handling!",
    "Courteous service and good attention to detail at {name}. We felt well taken care of throughout.",
    "Kudos to the serving team at {name}! They were polite, efficient, and very cooperative.",
    "Warm greeting at the entrance and respectful service at our table. {name} has a very good team!"
  ,
    // 51-60: Relaxing Experience
    "Had a relaxing afternoon at {name}. Quiet ambience, good Wi-Fi, and delicious cappuccino.",
    "Perfect place to unwind after a busy day! {name} provides a calm and peaceful sanctuary.",
    "Enjoyed a peaceful coffee break at {name}. Comfortable atmosphere and very polite staff.",
    "A refreshing break from the daily grind! {name} has a soothing vibe that helps you relax completely.",
    "Spent a lovely two hours at {name} catching up on reading while enjoying delicious iced coffee.",
    "The calm energy at {name} is wonderful. Great place to reflect, write, or have gentle conversations.",
    "If you need a quiet, comfortable cafe to relax, {name} is a top choice. Loved the vibe!",
    "Such a comforting space! {name} combines great coffee, soft music, and a peaceful atmosphere.",
    "Felt refreshed after visiting {name}. Good energy, pleasant people, and delicious refreshments.",
    "A serene retreat in the city! {name} offers the ideal environment to slow down and savor your meal."
  ,
    // 61-70: Clean & Pleasant
    "Very clean and hygienic cafe! Tables at {name} were spotless and cutlery was properly sanitized.",
    "Impressed with the neat and tidy setup at {name}. The premises and washrooms were very clean.",
    "Cleanliness and presentation at {name} are well maintained. Gives you great confidence in the food.",
    "Spotless dining area and fresh pleasant fragrance throughout {name}. Very well maintained venue!",
    "High standards of hygiene and care at {name}. Everything from table setting to glasses was sparkling clean.",
    "A well-kept and organized cafe! {name} takes cleanliness seriously and it really shows in the experience.",
    "Tidy booths, polished cutlery, and clean surroundings at {name}. Highly appreciate the hygiene.",
    "Everything looked clean and organized at {name}. Made our family meal very pleasant and comfortable.",
    "Spic and span dining area at {name}! Clean environment paired with delicious food makes it a winner.",
    "Clean, fresh, and properly sanitized! {name} provides a comfortable and safe dining space."
  ,
    // 71-80: Good Value & Portions
    "Good portion sizes and fair prices at {name}. Left the cafe feeling completely satisfied!",
    "Great value for money at {name}! Quality food, generous servings, and lovely ambience.",
    "Pocket-friendly prices for such good quality and atmosphere at {name}. Definitely worth visiting!",
    "The combos and platters at {name} offer excellent value. Tasty food that doesn't break the bank.",
    "Fair pricing and delicious meals at {name}. You get great food and great vibes for your money.",
    "Generous servings that easily satisfied our group at {name}. Good quality ingredients throughout.",
    "A cafe that gives you genuine value for what you spend! {name} hits the right balance of price and taste.",
    "Great portions, tasty preparation, and reasonable menu rates at {name}. Very pleased with the bill.",
    "Very satisfied with the food quality and portion sizes at {name}. Good value all around!",
    "Worth every penny spent! {name} offers great taste, clean surroundings, and friendly service."
  ,
    // 81-90: Meetups & Conversations
    "A fantastic spot for friends to meet up! {name} has spacious seating and delicious sharing plates.",
    "Met up with old friends at {name} and had a great time! The staff let us chat without rushing us.",
    "Ideal cafe for group conversations and birthday treats! {name} has plenty of room and good food.",
    "Had a great gathering at {name}. The sharing platters and mocktails kept everyone happy throughout.",
    "The seating arrangement at {name} is great for groups. Comfortable couches and lovely ambient music.",
    "Enjoyed a memorable evening with colleagues at {name}. Good snacks, great coffee, and nice vibes.",
    "Such a friendly community cafe! {name} is perfect for both casual chats and lively reunions.",
    "Had fun chatting over snacks and shakes at {name}. The staff took good care of our table.",
    "Great venue for an evening hangout! {name} has a welcoming vibe that makes everyone feel at home.",
    "Loved spending time with family at {name}. Everyone from kids to grandparents enjoyed the food."
  ,
    // 91-100: Overall Positive Impression
    "Really liked our experience at {name}! Good food, nice staff, and a pleasant overall atmosphere.",
    "A very solid and enjoyable cafe! {name} gets all the basics right and delivers with a smile.",
    "{name} has become one of my favorite spots in the area. Consistent taste and welcoming vibes.",
    "Had a wonderful time at {name}! Everything from drinks to desserts was well prepared.",
    "A warm and lovely dining experience at {name}. Highly recommend checking it out if you're nearby!",
    "Great place with positive energy! {name} is definitely worth a visit for good food and relaxation.",
    "Very pleased with our visit to {name}. The food tasted great and the ambience was lovely.",
    "A dependable cafe that never fails to please! {name} delivers good flavors and pleasant hospitality.",
    "Left {name} with a smile on our faces. Good food, nice music, and friendly staff throughout.",
    "Definitely coming back to {name} soon! A lovely place that made our evening truly delightful."
  ],

  2: [
    // 1-10: Cold & Bland Food
    "Very disappointed with the food at {name}. Everything arrived cold, bland, and lacked any real seasoning.",
    "The food at {name} was nearly unpalatable. Soggy fries, tasteless pasta, and totally cold by the time it arrived.",
    "Expected much better from {name}. The pizza base was rubbery, the sauce was sour, and the toppings were dry.",
    "Food quality was well below average at {name}. Stale buns, cold burger patty, and completely missing sauces.",
    "The dishes at {name} were drowning in excessive oil and lacked flavor. We couldn't finish even half of our meal.",
    "Very poor food execution at {name}. Soup was watered down and the garlic bread was burnt to a crisp.",
    "Tasteless and overpriced! The chef at {name} clearly cut corners today. Deeply unsatisfied with the quality.",
    "Had high hopes for {name}, but the food was a letdown. Cold dishes, tough meat, and dry bread all around.",
    "The taste was substandard at {name}. Flavors felt artificial and the dishes arrived lukewarm at best.",
    "Extremely bland food at {name}. Had to ask for extra salt, pepper, and oregano just to make it edible."
  ,
    // 11-20: Unacceptable Waiting Times
    "Waited over 45 minutes for two simple beverages and a starter at {name}. Completely disorganized kitchen!",
    "Terrible waiting times at {name}! People who arrived after us were served before us. Very frustrating experience.",
    "We spent more time waiting for our food than actually eating at {name}. Over 50 minutes of delay!",
    "Kitchen management at {name} is a disaster. Took an eternity to get basic sandwiches onto our table.",
    "If you are hungry, stay away from {name}. The waiting time is excruciatingly long with zero updates from staff.",
    "Had to ask the server four times about our order status at {name}. Still took nearly an hour to arrive.",
    "The delay ruined our lunch at {name}. We had to rush through our meal because of how late the food arrived.",
    "Horrible pacing at {name}. One dish came in 20 minutes, the next one took another 40 minutes. Completely disjointed.",
    "Waited 30 minutes just for drinks at {name}! No apology or explanation offered by the manager.",
    "Extremely slow turnaround time at {name}. The kitchen was clearly understaffed and couldn't handle the orders."
  ,
    // 21-30: Inattentive & Neglectful Staff
    "Service at {name} was completely inattentive. We had to wave our hands repeatedly just to get the waiter's attention.",
    "Staff at {name} seemed completely disinterested in serving customers. Felt like we were bothering them.",
    "Very poor hospitality at {name}. The staff ignored our calls and walked past our table multiple times.",
    "Nobody attended to our table for 15 minutes after we were seated at {name}. Had to fetch menus ourselves.",
    "The attitude of the servers at {name} was cold and dismissive. Customer service is practically nonexistent.",
    "Servers at {name} lacked basic training. Kept forgetting items we ordered and brought the wrong drinks twice.",
    "Neglectful service at {name}. Waited 20 minutes after finishing our meal just to get someone to bring the bill.",
    "The staff at {name} showed zero care for guest satisfaction. Very unwelcoming and robotic behavior.",
    "Had a terrible experience with the staff at {name}. Inattentive, unresponsive, and unapologetic.",
    "Floor staff at {name} was completely disorganized. No dedicated servers and nobody taking accountability."
  ,
    // 31-40: Overpriced & Poor Value
    "Total waste of money at {name}! Charged exorbitant prices for tiny portions of subpar quality food.",
    "The prices at {name} are ridiculous compared to what is served. You pay for the decor, but get terrible food.",
    "Horrible value proposition at {name}. Heavy bill with almost zero culinary satisfaction. Not worth it.",
    "Overpriced and under-delivered. {name} charges fine-dining rates for substandard cafe food.",
    "The bill shocked us considering how bad the food was at {name}. Would never spend money here again.",
    "Way too expensive for such poor portions and average taste at {name}. A thoroughly disappointing outing.",
    "Felt ripped off at {name}. High prices, small portions, and dishes that tasted like pre-packaged frozen food.",
    "Value for money is zero at {name}. You leave with an empty stomach and a significantly lighter wallet.",
    "Inflated prices without the quality to back it up at {name}. Don't fall for the social media photos.",
    "Extremely poor cost-to-satisfaction ratio at {name}. Definitely not recommending this to anyone on a budget."
  ,
    // 41-50: Order Mix-ups & Careless Errors
    "The staff at {name} messed up our entire order. Brought non-veg instead of veg, which is completely unacceptable!",
    "Got the wrong order twice at {name}. By the time they corrected it, everyone else at the table had finished eating.",
    "Careless mistakes at {name}! Ordered no cheese due to allergies, but the dish came loaded with cheese.",
    "Two items we ordered never showed up at {name}, but they were still added to our bill! Check your invoices.",
    "Confusion in the kitchen at {name}. Brought drinks meant for another table and argued when we pointed it out.",
    "Our order was mixed up completely at {name}. Servers seemed confused about table numbers and dish names.",
    "Ordered cold coffee and received a hot latte at {name}. Replaced it after 20 minutes with a watered-down version.",
    "Gross negligence in taking orders at {name}. Had to repeat simple instructions three times and still got it wrong.",
    "Wrong billing and wrong dishes at {name}. The staff seemed totally clueless about the menu offerings.",
    "Incorrect dishes served and zero apology from the management at {name}. Very sloppy operation."
  ,
    // 51-60: Uncomfortable Environment & Noise
    "The air conditioning was not working properly at {name}. It was uncomfortably hot and stuffy inside.",
    "Extremely loud, screeching music at {name}. Asked twice to lower the volume, but our request was ignored.",
    "The seating at {name} was horribly uncomfortable. Wobbly tables, cramped chairs, and zero legroom.",
    "Unpleasant dining environment at {name}. Flies buzzing around the indoor area and smoke from the kitchen.",
    "Suffocating atmosphere at {name}. Poor ventilation left the entire cafe smelling like burnt cooking oil.",
    "The venue at {name} was chaotic and loud. Felt more like a crowded railway station than a relaxing cafe.",
    "Dim lighting to the point where we couldn't even see what we were eating at {name}. Very frustrating.",
    "Wobbly table caused our drinks to spill at {name}, and staff took ten minutes just to bring a mop.",
    "Noise levels were unbearable at {name}. Screaming patrons and loud speakers made it a headache-inducing meal.",
    "Poor climate control at {name}. Either freezing cold right under the AC vent or boiling hot elsewhere."
  ,
    // 61-70: Hygiene Concerns
    "Cleanliness at {name} was alarming. The table had sticky sauce residues and cutlery was visibly soiled.",
    "Found hair in our food at {name}! When pointed out, the server merely shrugged and took the plate away.",
    "Dirty glasses and spotted spoons at {name}. Had to ask for replacements twice. Basic hygiene is ignored.",
    "The washroom was filthy and smelled awful at {name}. Completely ruined our appetite for the meal.",
    "Dusty cushions and dirty floor corners at {name}. Clearly lacks proper daily cleaning and sanitation.",
    "Observed the staff at {name} handling food and ice with bare hands after touching money. Very concerning.",
    "Unwashed glasses served to our table at {name}. You could see lipstick marks from previous customers!",
    "Flies and fruit flies hovering around the pastry display at {name}. Very unhygienic presentation.",
    "The ketchup bottle at our table in {name} was crusty and expired. Disgusting lack of cleanliness.",
    "Severe hygiene shortcomings at {name}. If the front of house is this dirty, I worry about the kitchen."
  ,
    // 71-80: Bad Drinks & Coffee
    "The coffee at {name} was bitter, burnt, and tasted like it was brewed with stale beans. Undrinkable!",
    "Ordered two mocktails at {name} and both were just cheap artificial syrup mixed with flat soda. Awful.",
    "Watery, flavorless shakes at {name}. Charged premium prices for what tasted like milk mixed with tap water.",
    "The cold brew at {name} was sour and completely flat. Easily one of the worst coffees I've had in the city.",
    "Drinks arrived lukewarm with melted ice at {name}. Zero freshness and totally lacked proper presentation.",
    "The tea at {name} was over-steeped, bitter, and served in a stained ceramic mug. Very disappointing.",
    "Ordered their signature beverage at {name} and it tasted like cough syrup. Couldn't take more than two sips.",
    "The smoothie at {name} had ice crystals and separated within two minutes. Very poorly made.",
    "Burnt espresso shots ruined the latte at {name}. Barista needs proper training on machine calibration.",
    "Flat soda and stale mint leaves ruined our drinks at {name}. Threw away half the glass."
  ,
    // 81-90: Poor Management
    "Spoke to the manager at {name} regarding our issues, and was met with arrogance and defensiveness.",
    "Management at {name} takes zero accountability. Blamed the kitchen staff in front of us rather than fixing the issue.",
    "Total lack of professionalism from the managerial team at {name}. They seemed unbothered by customer feedback.",
    "No supervisor on the floor at {name}. Junior staff had no guidance and chaos was visible everywhere.",
    "When we complained about cold food at {name}, the manager argued that this is how the dish is supposed to taste!",
    "Poor leadership at {name} reflects in the chaotic service and substandard food quality. Needs serious intervention.",
    "The floor manager at {name} showed zero empathy or problem-solving skills. Disappointing customer handling.",
    "Management at {name} only caters to VIPs or their friends. Regular walk-in guests are completely neglected.",
    "Arrogant management at {name}. A simple apology would have sufficed, but instead they gave defensive excuses.",
    "Total management failure at {name}. Disorganized seating, lost orders, and uncaring managerial attitude."
  ,
    // 91-100: Regret & Negative Recommendation
    "Deeply regret choosing {name} for our evening out. It was a stressful, unsatisfying experience from start to finish.",
    "Would not recommend {name} to anyone. There are far better cafes nearby that offer genuine quality and care.",
    "Save your money and go elsewhere! {name} relies solely on fake hype while delivering 2-star food and service.",
    "Huge disappointment at {name}. The reality is light years away from what is shown on their social media page.",
    "Won't be returning to {name}. Too many flaws in food, speed, hygiene, and service to ever justify coming back.",
    "2 stars only for the interior design, because everything else at {name} was thoroughly disappointing.",
    "Left {name} with a sour taste in our mouths and an empty stomach. A complete letdown of an outing.",
    "Don't waste your time or hard-earned money at {name}. Too many operational issues and subpar food.",
    "One of the most disappointing cafe experiences this year at {name}. Needs massive improvements across the board.",
    "Avoid {name} if you value good food, prompt service, or respectful treatment. Very underwhelming."
  ],

  1: [
    // 1-10: Extremely Rude Staff & Hostility
    "Horrendous experience at {name}! The staff was shockingly rude, argumentative, and behaved with total disrespect.",
    "Never been treated so poorly at a cafe! The waiter at {name} literally rolled his eyes and threw the bill on our table.",
    "Abysmal behavior from the staff at {name}! Extremely hostile and uncouth attitude towards paying customers.",
    "The manager at {name} was obnoxious and arrogant when we pointed out a genuine problem. Zero hospitality sense!",
    "Staff at {name} displayed utter contempt for customers. We were insulted for asking to change a dirty glass!",
    "Disgraceful service at {name}. Staff was yelling across the hall and treated our family with shocking rudeness.",
    "The level of disrespect from the staff at {name} was appalling. Will never step foot into this place again.",
    "Extremely arrogant management and staff at {name}. Treated us like they were doing us a favor by serving us.",
    "The staff at {name} ruined our day with their toxic attitude. A cafe that treats patrons like this should be shut down.",
    "Rude, hostile, and utterly unprofessional. The team at {name} has no business working in the hospitality sector."
  ,
    // 11-20: Rotten, Stale & Inedible Food
    "The food served at {name} was rotten and smelled awful! Had to spit it out immediately. Disgusting and dangerous!",
    "Suffered from severe food poisoning after dining at {name}! Stale ingredients, foul-tasting meat, and rancid oil.",
    "Inedible food! The chicken at {name} was completely raw inside while the outside was burnt. Hazardous to health!",
    "Food quality at {name} is pathetic. Tasted like leftovers that were repeatedly reheated over several days.",
    "The cheese was sour and expired on the pizza at {name}. Absolute health hazard! Avoid eating here at all costs.",
    "Disgusting food quality at {name}. Sour dairy, stale bread, and unwashed vegetables. Couldn't eat a single bite.",
    "Food smelled rotten at {name}. When we told the manager, he was rude and insisted on charging us anyway!",
    "Completely spoiled food served at {name}. Rancid smell coming from the gravy. Truly stomach-turning experience.",
    "The worst food I have ever been served in my entire life was at {name}. Stale, cold, and utterly repulsive.",
    "Zero hygiene in the kitchen at {name}! Rotten ingredients, stale sauces, and completely unsafe food."
  ,
    // 21-30: Gross Hygiene & Foreign Objects
    "Found an insect inside my drink at {name}! Absolutely revolting! Zero standards of hygiene and pest control.",
    "There was a dead fly inside our soup at {name}! The staff didn't even apologize, just took the bowl away.",
    "Cockroaches spotted crawling on the wall next to our dining table at {name}! Beyond disgusting and unacceptable.",
    "Found a strand of metal wire in the food at {name}! Could have caused serious medical injury. Shockingly careless!",
    "Stray pests inside the dining area and filthy kitchen conditions visible at {name}. Absolute health hazard!",
    "The glasses and plates at {name} had dried food remnants from previous diners. Pure filth and unhygienic neglect.",
    "Found plastic packaging melted inside our baked pasta at {name}! Unbelievably reckless kitchen standards.",
    "The dining area at {name} smelled like an open sewer. Filthy floors, stained tables, and zero sanitation.",
    "Hair in the starter and insect in the main course at {name}! Two contaminated dishes in one meal. Horrific!",
    "Extremely unhygienic! The kitchen at {name} looks like a disaster zone. Food safety authorities must inspect this."
  ,
    // 31-40: Extreme Delays & Abandonment
    "Waited 1 hour and 15 minutes at {name} and food NEVER arrived! We had to walk out hungry and furious.",
    "Complete disaster at {name}! They lost our order slip, made us wait 70 minutes, and then admitted they forgot!",
    "Ordered two coffees and waited over 50 minutes at {name}. Nobody cared, nobody checked, zero service!",
    "We were totally abandoned at our table in {name}. Over an hour wait with empty glasses and zero updates.",
    "Walked out of {name} after waiting 80 minutes without getting a single dish! Worst cafe management ever seen.",
    "Kitchen forgot about our table completely at {name}. When we asked after an hour, they asked us to re-order!",
    "Excruciating 90-minute delay at {name}! Left the venue famished and thoroughly aggravated. Total failure.",
    "Took over an hour for basic french fries and a soda at {name}. Absolute mockery of customer service.",
    "Kept telling us '5 more minutes' for over an hour at {name}. Total dishonesty and pathetic coordination.",
    "Waited forever at {name} while the staff stood around doing nothing. Walked out without eating. Horrible place!"
  ,
    // 41-50: Overcharging, Fraud & Billing Scams
    "Complete scam at {name}! Added extra items to our bill that we never ordered and refused to remove them.",
    "Check your bills carefully at {name}! They overcharge on taxes, sneak in extra charges, and argue aggressively.",
    "Charged us for premium bottled water when they actually served regular tap water at {name}! Unethical scam!",
    "Billing fraud at {name}! Prices on the printed invoice were 30% higher than the menu prices shown to us.",
    "Disputed an unauthorized surcharge at {name} and the cashier threatened and misbehaved with us. Shocking!",
    "Charged us twice for the same dish on the credit card machine at {name} and refused to process a refund.",
    "Hidden fees, mandatory tips forced on customers, and bogus service charges at {name}. Complete daylight robbery!",
    "The cashier at {name} was blatantly dishonest. Tried to pocket the change and argued when called out.",
    "Overpriced menu followed by fraudulent billing items at {name}. Completely unethical business practices!",
    "They charged us for dishes that were sent back untouched due to being spoiled at {name}. Shameless greed!"
  ,
    // 51-60: Ruined Celebrations & Special Days
    "{name} completely ruined our anniversary celebration! Terrible food, rude staff, and chaotic service. Devastated.",
    "Booked a table for my daughter's birthday at {name} and they gave our table away to someone else! Heartbreaking.",
    "Our family gathering was turned into a nightmare by the incompetent staff at {name}. Ruined our special day.",
    "Planned a special dinner at {name} and it turned into the most embarrassing, frustrating night of the year.",
    "Celebrated a major milestone at {name} and was met with raw food, delayed service, and rude managers. Ruined!",
    "Total catastrophe! {name} ruined our family reunion. Cold food, dirty tables, and an argumentative manager.",
    "Do NOT plan any celebration at {name}! They will ruin your mood, your party, and your memories completely.",
    "Worst birthday dinner ever at {name}! Waited an hour, got incorrect orders, and staff was completely unapologetic.",
    "Brought out-of-town guests to {name} and was thoroughly embarrassed by the abysmal quality and service.",
    "Our evening was completely wrecked by the staff and kitchen at {name}. Unforgivable lack of competence!"
  ,
    // 61-70: Total Chaos & Kitchen Meltdown
    "Absolute circus at {name}! Waiters dropping plates, kitchen shouting, wrong tables served, pure pandemonium.",
    "Total breakdown of operations at {name}. Staff running around headless while food sits rotting on counters.",
    "The kitchen at {name} is in complete chaos. Orders mixed up, food coming out cold, and staff yelling at each other.",
    "Never seen such unprofessionalism! The staff at {name} were having loud arguments in front of paying guests.",
    "Uncontrollable chaos at {name}. Waited 40 minutes only to be told they lost our order ticket. Incompetence peak!",
    "Zero management oversight at {name}. Customers shouting, tables uncleared, and kitchen completely backed up.",
    "A total logistical disaster! {name} accepts more guests than they can handle and everything crashes down.",
    "Disorganized, noisy, and chaotic beyond words at {name}. Nobody knows who is cooking or who is serving.",
    "Sloppy, reckless, and dysfunctional operation at {name}. One of the worst run establishments in the city.",
    "Total mismanagement at {name}! If you want peace and proper food, this place is the exact opposite."
  ,
    // 71-80: Toxic Environment & Safety
    "Felt completely unsafe and unwelcome at {name}. Unruly crowd, no security, and staff did nothing to intervene.",
    "The venue at {name} was smoky, suffocating, and hazardous. Zero air ventilation or fire safety visible.",
    "Bouncers and staff at {name} behaved aggressively with patrons. Terrible, toxic atmosphere!",
    "Unsafe and hazardous setup at {name}. Wires dangling near tables and broken tiles on the walkway. Avoid!",
    "Aggressive behavior from the security and staff at {name}. Threatening attitude towards regular customers.",
    "Zero crowd management or safety measures at {name}. Crammed so many people inside that exits were blocked.",
    "Very shady and uncomfortable environment at {name}. Would never recommend families or women to visit.",
    "Staff at {name} encouraged an unruly group creating nuisance instead of maintaining decorum. Dreadful.",
    "Poor lighting, slippery wet floors with no warning signs, and zero care for guest safety at {name}.",
    "Hostile, aggressive, and toxic atmosphere at {name}. One of the worst dining experiences imaginable."
  ,
    // 81-90: Absolute Disgust & Stomach Illness
    "Got severe food poisoning within hours of eating at {name}. Spent two days in bed with stomach cramps. Toxic!",
    "My entire family fell sick after eating the pasta and pizza at {name}! Pure poison being served in the name of food.",
    "The food at {name} was stale, rancid, and gave me acute gastroenteritis. AVOID AT ALL COSTS!",
    "Terrible stomach infection after visiting {name}. The dairy products were clearly spoiled and foul. Disgraceful!",
    "Fell violently ill after dining at {name}. Never felt so sick from restaurant food in my life. Never again!",
    "Stomach flu caused by the contaminated food and water at {name}. Total negligence towards health safety.",
    "Woke up with severe nausea and fever after eating at {name}. Inexcusable lack of hygiene and food quality.",
    "Medical nightmare after visiting {name}. Doctor confirmed bacterial food contamination from undercooked food.",
    "Poisonous food being served at {name}! Stale, infected, and completely unhygienic. Health authorities take note!",
    "Both my friend and I developed food poisoning from {name}'s starters. Pathetic and unforgivable standards."
  ,
    // 91-100: Definitive 1-Star Verdicts
    "Zero stars if I could! {name} is by far the worst cafe experience in existence. Stay as far away as possible!",
    "Do NOT visit {name}! Total waste of money, terrible food, rude staff, and complete disrespect for guests.",
    "A complete nightmare from beginning to end! {name} fails on food, fails on hygiene, and fails on service.",
    "Save yourself the headache, money, and stomach ache. Avoid {name} like the plague! Absolute disaster.",
    "I would give minus stars to {name} if Google allowed it. Utterly appalling and pathetic establishment.",
    "Never coming back, never recommending. {name} is the gold standard for how NOT to run a restaurant.",
    "The worst dining decision of my life was walking into {name}. Pathetic food, filthy place, and rude staff.",
    "Warning to everyone: Avoid {name}! Overpriced garbage food, hostile management, and filthy premises.",
    "A catastrophic failure in every possible way. {name} does not deserve a single customer. Disgraceful!",
    "Worst cafe in the entire city! {name} is a complete fraud. Save your hard-earned money and eat elsewhere."
  ]
}
