// 500 Unique Review Templates (100 per rating 1 to 5)
// All templates support dynamic `{name}` replacement.

export const REVIEW_TEMPLATES: Record<number, string[]> = {
  5: [
    // 1-10: Ambiance & Aesthetics
    "Absolutely blown away by the stunning ambiance at {name}! The lighting, aesthetics, and cozy seating make it the best hangout spot.",
    "The vibe at {name} is unmatched! Beautiful interior decor, great background music, and a very relaxing atmosphere.",
    "{name} is an aesthetic paradise! Every corner is Instagram-worthy, and the overall vibe is super chill.",
    "Loved the rooftop and interior setup at {name}. Perfect lighting, comfortable seating, and wonderful music playlist.",
    "The mood and decor at {name} set the bar really high. Easily one of the most beautiful cafes in town!",
    "Had the most relaxing evening at {name}! The warm golden ambience and soothing music make it a 10/10 experience.",
    "From the entrance to the seating, {name} oozes charm and elegance. A truly upscale cafe experience!",
    "{name} has such a warm, inviting energy. The open-air vibe combined with classy interiors made our visit unforgettable.",
    "A gorgeous place with incredible attention to detail! {name} is definitely my new favorite spot to unwind.",
    "The atmosphere at {name} is pure magic. Great crowd, fantastic decor, and an energetic yet peaceful vibe.",

    // 11-20: Food Taste & Quality
    "The food at {name} was nothing short of perfection! Every single dish was bursting with fresh, authentic flavors.",
    "Incredible culinary experience at {name}! The pasta and wood-fired pizza were cooked to absolute perfection.",
    "Hands down the tastiest cafe food I've had in a long time! {name} nailed every dish we ordered today.",
    "Delicious food with five-star presentation! {name} truly takes pride in the quality of ingredients they use.",
    "The flavors at {name} are extraordinary! Freshly prepared, well-seasoned, and served piping hot. Truly impressed!",
    "Every bite at {name} was a delight! Whatever you do, don't miss out on their signature appetizers and main courses.",
    "Top-notch gastronomic experience at {name}! The chef deserves huge praise for crafting such delicious recipes.",
    "Food lovers, rejoice! {name} delivers gourmet quality food in a relaxed, comfortable cafe setting. Loved it!",
    "The gourmet platters at {name} exceeded all expectations. Fresh ingredients, delightful sauces, and great aroma.",
    "Sensational food! Everything from the crispy starters to the flavorful mains at {name} was top tier.",

    // 21-30: Beverages, Coffees & Drinks
    "The coffee at {name} is artisan quality! Perfectly brewed, rich crema, and incredible aroma. Best brew in town!",
    "Had the most refreshing mocktails at {name}! Perfectly balanced sweetness, beautifully presented, and super chilled.",
    "If you love specialty coffee, {name} is the place to be! Their cold brews and lattes are second to none.",
    "The beverage menu at {name} is phenomenal! Great variety of coolers, shakes, and premium artisanal teas.",
    "Tried their signature coolers and handcrafted coffee at {name} - both were utterly refreshing and perfectly blended.",
    "Kudos to the baristas at {name}! My cappuccino was velvety smooth and had gorgeous latte art on top.",
    "The shakes and smoothies at {name} are thick, rich, and made with genuine quality ingredients. 5 stars!",
    "Such creative beverages at {name}! Every drink looks stunning and tastes even better. Highly recommended!",
    "The iced latte and fruit coolers at {name} were pure bliss on a warm afternoon. Can't wait to order again!",
    "A haven for coffee lovers! {name} brews some of the smoothest, most flavorful coffee you will find anywhere.",

    // 31-40: Hospitality & Service
    "The hospitality at {name} is world-class! The team was so polite, attentive, and made us feel truly welcomed.",
    "Outstanding customer service at {name}! The staff greeted us with genuine smiles and offered great recommendations.",
    "Remarkable staff at {name}! They took care of our custom dietary requests effortlessly and checked in regularly.",
    "Service with a smile! The servers at {name} are courteous, efficient, and genuinely passionate about hospitality.",
    "Felt like royalty dining at {name}! The attentiveness and professionalism of the staff were second to none.",
    "The staff at {name} went above and beyond to make our dining experience comfortable. Exceptional service!",
    "Prompt, polite, and thoroughly professional staff at {name}. They made our family dinner smooth and delightful.",
    "Huge shoutout to the serving team at {name}! Quick on their feet and always ready with helpful suggestions.",
    "Warm hospitality and swift service! {name} knows exactly how to treat its guests right from start to finish.",
    "The management and staff at {name} are doing a phenomenal job. Courteous, prompt, and very accommodating!",

    // 41-50: Celebrations & Group Outings
    "Celebrated my birthday at {name} and it was unforgettable! The staff helped us organize everything seamlessly.",
    "The best venue for celebrations! We hosted a friends' reunion at {name} and everyone had a blast.",
    "Had a group party at {name} and the vibes were electric! Plenty of space, great music, and delicious sharing platters.",
    "Celebrated our anniversary at {name} and it couldn't have been more romantic. Thank you for the special hospitality!",
    "Great place for hosting private get-togethers! {name} managed our large group order with total efficiency and grace.",
    "Our family get-together at {name} was a massive hit! Kids and elders alike thoroughly enjoyed the food and setting.",
    "Hosted an office celebration at {name} - prompt service, spacious seating, and delicious finger food throughout.",
    "If you're planning any celebration or weekend party, {name} is the top choice. The atmosphere is vibrant and joyful!",
    "Unforgettable evening celebrating with friends at {name}! The music, food, and drinks kept the spirits high all night.",
    "Special occasions deserve special places, and {name} made our milestone celebration truly magical!",

    // 51-60: Date Nights & Couples
    "The perfect date night destination! {name} offers cozy corners, romantic candlelit vibes, and delicious cuisine.",
    "Took my partner to {name} for a romantic dinner, and we both fell in love with the serene and intimate setting.",
    "Romantic music, dim aesthetic lighting, and delectable dishes make {name} the ultimate date spot in the city.",
    "Such a romantic and charming ambiance at {name}! Ideal for couples looking for a cozy, upscale dining experience.",
    "An intimate culinary escape! {name} set the mood perfectly for our date night with soft jazz and warm hospitality.",
    "If you want to impress your date, take them to {name}. The food, the drinks, and the view are unbeatable.",
    "Loved the private, cozy vibe at {name}. A beautiful retreat away from the city hustle for couples.",
    "Everything about {name} screams elegance and romance. Delicious food paired with a dreamy, relaxing vibe.",
    "Our romantic dinner at {name} was straight out of a movie! Quiet corners, stellar food, and sweet background music.",
    "Can't think of a better place for a couple's evening than {name}. Absolute perfection in every department!",

    // 61-70: Work & Casual Hangouts
    "Great place to work remotely or read a book! {name} has comfortable seating, quiet spots, and great coffee.",
    "Spent a productive afternoon working at {name}. High-speed vibes, tasty snacks, and endless cups of great coffee.",
    "Super relaxed cafe! {name} is the ideal spot to catch up with colleagues or just spend some peaceful me-time.",
    "Comfortable chairs, calm ambient music, and great lattes make {name} a brilliant workspace during daytime.",
    "Whether you're working on your laptop or chilling with buddies, {name} provides the most welcoming environment.",
    "Peaceful, chic, and comfortable. {name} is the ultimate daytime retreat for creative minds and remote workers.",
    "A cozy sanctuary! Spent three hours at {name} reading and sipping on their special brews. Pure relaxation.",
    "{name} has the perfect balance of lively energy and peaceful seating. Ideal for casual afternoon meetings.",
    "My favorite neighborhood cafe! {name} is always clean, welcoming, and perfect for getting work done over coffee.",
    "Great Wi-Fi, comfortable booths, and delicious coffee - {name} is an absolute gem for casual day-outs.",

    // 71-80: Desserts & Bakery
    "The desserts at {name} are heavenly! Rich chocolate indulgence, perfectly balanced sweetness, and exquisite texture.",
    "Save room for dessert when visiting {name}! Their cheesecake and artisan pastries are truly world-class.",
    "Sweet tooth heaven! The warm brownie and artisanal desserts at {name} melted right in our mouths.",
    "The bakery items at {name} taste like they came straight out of a Parisian patisserie. Utterly divine!",
    "Had the most decadent dessert at {name}! Premium chocolate, fresh berry coulis, and stunning visual presentation.",
    "Do yourself a favor and order their desserts at {name}. Freshly baked, perfectly moist, and full of rich flavors.",
    "The tiramisu at {name} is hands down the best in town. Light, authentic, and perfectly balanced with coffee notes.",
    "Every dessert at {name} looks like a piece of art and tastes even better. Simply unmatched sweet treats!",
    "A sweet lover's dream! The warm waffle and ice cream pairing at {name} was the perfect end to our feast.",
    "Dessert perfection! {name} serves freshly crafted bakery delights that leave you craving more.",

    // 81-90: Speed & Consistency
    "Always consistent and always fantastic! This is my fourth visit to {name} and every experience has been 5 stars.",
    "Impressive kitchen speed at {name}! Our food arrived piping hot and fresh within minutes of placing the order.",
    "Consistently outstanding! No matter what time of day you visit, {name} always delivers top quality and warmth.",
    "Zero delays and flawless execution at {name}. The food arrived together, hot, and tasting extraordinary.",
    "Quick table turnaround and seamless ordering. {name} runs like a well-oiled machine without cutting corners.",
    "Consistency is key, and {name} never fails to impress. Great taste, swift service, and immaculate cleanliness.",
    "Food arrived remarkably fast without compromising an ounce of quality or presentation at {name}. Superb!",
    "I've been a regular customer at {name} for months now, and the quality has remained stellar on every single trip.",
    "Fast, fresh, and exceptionally delicious! {name} handles busy dinner rushes with effortless professionalism.",
    "From greeting to bill settlement, the service at {name} was swift, efficient, and thoroughly pleasant.",

    // 91-100: Overall Stellar Impression
    "{name} is an absolute gem! Superb food, gorgeous decor, and unforgettable hospitality. Highly recommended to all!",
    "Without a doubt, {name} is one of the premier cafes in the region. Everything they do, they do with excellence.",
    "An extraordinary dining destination! {name} checks all the right boxes: taste, vibe, hygiene, and service.",
    "Can't say enough good things about {name}! Five stars aren't enough to capture how wonderful our experience was.",
    "A must-visit spot for both locals and travelers! {name} is setting a new benchmark for cafe culture.",
    "Everything about {name} exceeded our wildest expectations. We are already planning our next visit!",
    "Absolute perfection! {name} has earned a lifelong fan in me. Will be recommending this place to all my friends.",
    "Pure elegance and culinary delight! {name} delivers an all-round five-star experience that you won't forget.",
    "A truly sensational cafe! {name} combines culinary artistry with warm vibes. Don't think twice, just visit!",
    "Top tier in every single category! {name} is a shining star in the city's food scene. 10/10 recommendation!"
  ],

  4: [
    // 1-10: Great Food, Slight Wait
    "Really enjoyed our visit to {name}! The food was mouth-watering, though the kitchen took a few extra minutes during the rush.",
    "Delicious meal at {name}! Everything tasted wonderful and fresh. Just a slight wait for the main course, but worth it.",
    "Great flavors at {name}! The pizza and appetizers were superb. Service was slightly delayed, but the team was very polite.",
    "Had a lovely lunch at {name}. The pasta was authentic and rich. A small wait for the order, but we really enjoyed our time.",
    "The taste of the food at {name} was top quality! A minor delay during peak dinner time, but overall a solid experience.",
    "Wonderful flavors at {name}! Starters came fast, while mains took slightly longer, but the taste made up for it completely.",
    "Food was exceptional at {name}! Just took a bit longer than expected to arrive, but the staff kept us updated nicely.",
    "Tasty and wholesome food at {name}! The kitchen was packed on a Saturday evening, but the flavors were well worth the wait.",
    "Loved the recipes at {name}! The burgers and fries were delicious. Service could be a minute faster, but overall very happy.",
    "Really good culinary standards at {name}. High quality ingredients and great taste, with just a tiny wait on starters."
  ,
    // 11-20: Lovely Ambiance, Busy Peak Hours
    "The ambiance at {name} is gorgeous! It was quite packed when we arrived, but the staff managed seating very well.",
    "Super cozy vibe at {name}! Beautiful lights and decor. It gets lively and crowded on weekends, so arrive early.",
    "Loved the aesthetic interiors of {name}! Seating was full initially, but once seated, we had a very pleasant time.",
    "Very stylish cafe with pleasant decor! {name} gets quite busy in the evenings, but the vibe remains enjoyable.",
    "{name} has such a charming setup. A little bustling during peak hours, but the overall atmosphere is delightful.",
    "Great background music and beautiful seating at {name}. It was quite crowded, but the staff handled it gracefully.",
    "Lovely place to hang out with friends! {name} has great energy, though finding a prime table on weekends takes patience.",
    "The rooftop atmosphere at {name} is fantastic. A bit breezy and busy, but the overall ambiance is definitely a 4-star.",
    "Really charming interior aesthetics at {name}. High footfall during dinner, but they accommodated us warmly.",
    "Warm, rustic, and pleasant ambiance at {name}! Peak hours are crowded, but it speaks volumes about their popularity."
  ,
    // 21-30: Delicious Coffee & Beverages
    "Great coffee at {name}! The brew was strong and flavorful. Pastry selection was slightly limited, but the drinks rocked.",
    "Loved the iced teas and smoothies at {name}! Refreshing and well-made. A great spot for an afternoon beverage.",
    "Coffee lovers will appreciate {name}! Great cappuccino and latte. Would love to see more dairy-free milk options.",
    "Refreshing mocktails and tasty finger food at {name}. The drinks were presented beautifully, tasted crisp and fresh.",
    "Had a great cold brew at {name}! Perfect temperature and strength. Snacks were good, overall a very pleasant afternoon.",
    "The beverage menu at {name} has plenty of variety. Our drinks were delicious and served chilled. Very satisfying!",
    "Great artisanal brews at {name}! The coffee was on point. Service was polite, definitely returning for my morning cup.",
    "Loved the fruit coolers at {name}! Perfect balance of sweet and tangy. Good food pairings available too.",
    "Very good shakes and frappes at {name}! Rich texture and great taste. A solid 4-star experience.",
    "The hot chocolate and cappuccinos at {name} were comforting and rich. Lovely drink options throughout the menu."
  ,
    // 31-40: Friendly Staff with Minor Feedback
    "Staff at {name} was very courteous and accommodating! Just took a little time to flag down a waiter for the bill.",
    "Pleasant hospitality at {name}! The servers were friendly and patient while taking our customized order.",
    "The team at {name} is warm and polite. A bit overwhelmed during the weekend rush, but they tried their best.",
    "Good service at {name}! Staff gave great food recommendations that we enjoyed. Fast and courteous demeanor.",
    "Friendly smiles from the staff at {name}. Service had a slight hiccup with one drink, but they resolved it promptly.",
    "Helpful and well-mannered staff at {name}. They made sure our table had water and checked in on our satisfaction.",
    "Staff at {name} greeted us warmly. A tiny delay in clearing plates, but overall very friendly and attentive.",
    "Courteous team members at {name}. They explained the menu items nicely and made us feel comfortable throughout.",
    "Prompt greeting and good manners from the crew at {name}. Kept the dining experience enjoyable from start to finish.",
    "The hospitality at {name} is definitely commendable. Hard-working staff doing their best during peak hours."
  ,
    // 41-50: Pleasant Vibe & Music
    "Good music playlist at {name}! Set a lovely mood for our dinner. Volume was slightly loud for talking, but still nice.",
    "Enjoyed the playlist and vibe at {name}. Cozy lighting and great acoustics. Makes for a relaxing hangout.",
    "The mood lighting at {name} creates an intimate setting. Music was modern and upbeat. We had a great time.",
    "Nice tunes playing in the background at {name}. Comfortable couches and relaxed seating arrangements.",
    "The vibe at {name} is lively yet comforting. Music could be turned down a notch, but overall very positive.",
    "Pleasant background melodies at {name} that didn't overpower conversation. Great cafe aesthetic all around.",
    "Loved the evening lighting and chill beats at {name}. A great spot to unwind after a long working day.",
    "Fun and upbeat environment at {name}. Clean tables, cozy corners, and good music make it a very nice visit.",
    "Chill vibes throughout {name}! Perfect background soundtrack for chilling with close friends on a weekend.",
    "The interior acoustics and music choices at {name} were enjoyable. Felt relaxed from the moment we walked in."
  ,
    // 51-60: Value & Portion Sizes
    "Good portion sizes and fair pricing at {name}. The food was tasty and filled us up well. Solid value for money.",
    "Reasonably priced menu at {name} given the upscale ambiance and fresh ingredients. We were very satisfied.",
    "Generous servings for starters at {name}! Mains were slightly smaller in portion, but the taste was very good.",
    "Good value for an upscale cafe experience at {name}. Quality was evident in every dish served to us.",
    "Fair pricing structure at {name}. Tasty food and quality beverages without exorbitant charges. Well done!",
    "Decent portion sizes and great seasoning at {name}. Left the cafe feeling satisfied and pleased with the meal.",
    "Price matches the quality and aesthetic at {name}. Everything tasted fresh and well-prepared.",
    "Satisfying meal portions at {name}! We shared a couple of platters and were full by the end. Good experience.",
    "The combo meals and platters at {name} offer good value. Tasty options for casual dining with friends.",
    "Good balance of quality and pricing at {name}. Worth visiting for both casual coffee and full meals."
  ,
    // 61-70: Casual Hangout & Cleanliness
    "Clean and hygienic setup at {name}! Sanitized tables, clean cutlery, and a very fresh atmosphere throughout.",
    "Great spot for hanging out with friends! {name} has spacious seating and clean washrooms. Very respectable place.",
    "Impressed with the hygiene standards at {name}. Everything looked clean, tidy, and well-maintained.",
    "A dependable place to meet friends! {name} is comfortable, tidy, and serves delicious quick bites.",
    "Comfortable seating and well-maintained interiors at {name}. A pleasant cafe to spend an hour or two chatting.",
    "Spotless dining area and quick table cleanup at {name}. It's great to see a cafe that takes cleanliness seriously.",
    "Nice and airy setup at {name}. Tables are well-spaced so you don't feel cramped even when it's busy.",
    "Great cafe to lounge around on a lazy afternoon. {name} has friendly staff and a clean, relaxed environment.",
    "Neat and organized cafe! {name} delivers on cleanliness, comfort, and enjoyable cafe bites every time.",
    "Good hygiene, tidy tables, and comfortable booths at {name}. Definitely one of the cleaner cafes around."
  ,
    // 71-80: Varied Menu & Presentation
    "Extensive menu with lots of appetizing options at {name}! One or two items were unavailable, but the rest were great.",
    "Food presentation at {name} is lovely! Very photogenic plating and delicious taste to back it up.",
    "Creative menu at {name}! Good variety of continental and fusion dishes. We enjoyed our selection thoroughly.",
    "Nicely curated food options at {name}. The presentation of starters was appetizing and colorful. Solid 4 stars.",
    "Appreciated the diverse options on {name}'s menu. Something for everyone, whether you want light snacks or hearty meals.",
    "The platters at {name} looked stunning when they arrived at our table. Good flavors to match the visual appeal.",
    "Impressive menu selection at {name}! Tried three new dishes today and each had a unique, pleasant flavor profile.",
    "Great variety of vegetarian and non-vegetarian choices at {name}. Plating was neat and appetite-inducing.",
    "Good culinary choices on the menu at {name}. Chef clearly puts thought into presentation and garnishing.",
    "Well-designed menu with clear descriptions at {name}. The food looked just as good as pictured."
  ,
    // 81-90: Overall Experience
    "Overall a very positive experience at {name}! Delicious food, nice ambiance, and reasonable waiting times.",
    "Had an enjoyable time at {name}. A few minor things could be refined, but definitely a strong 4-star venue.",
    "Solid cafe experience at {name}! Great for casual meetups, dates, or family tea time. Will visit again.",
    "Enjoyed the dining experience at {name}. The staff is polite, food is tasty, and the location is convenient.",
    "A very good cafe that gets most things right! {name} has become our go-to spot for casual evening snacks.",
    "Very pleased with our evening at {name}. Small wait on food, but overall quality and hospitality were commendable.",
    "Good food, good vibes, and good company at {name}. A reliable place for an enjoyable meal.",
    "Comfortable ambiance and flavorful food make {name} well worth a visit. Happy with the overall service.",
    "Had a wonderful time at {name}! Will gladly bring more friends along on our next visit.",
    "Solid 4-star performance by {name}. Well managed, tasty dishes, and lovely ambient atmosphere."
  ,
    // 91-100: Recommendations
    "Would definitely recommend {name} to anyone looking for good food and a trendy vibe in the area!",
    "Great addition to the cafe scene! {name} delivers consistent quality and a warm welcoming atmosphere.",
    "A solid choice for evening coffee or dinner! {name} impressed us with its flavors and courteous staff.",
    "Happy to recommend {name}! A lovely venue with great food and a relaxed, contemporary vibe.",
    "Definitely worth checking out! {name} offers good food, cozy seating, and a warm neighborhood feel.",
    "Recommended for anyone who enjoys good food in a trendy setting. {name} does not disappoint.",
    "A very satisfying visit to {name}! I will be returning soon to explore more of their signature menu items.",
    "If you're in the neighborhood, {name} is a reliable choice for delicious snacks and refreshing drinks.",
    "Thumbs up to {name}! Great ambiance, friendly staff, and tasty dishes that leave you satisfied.",
    "Really good experience at {name}. With just a tiny speed bump fixed in the kitchen, it would easily be 5 stars!"
  ],

  3: [
    // 1-10: Average Taste
    "An average experience at {name}. The food was decent, but nothing truly stood out in terms of flavor.",
    "Food at {name} was okay. Not bad, but didn't have that wow factor I was expecting from the photos.",
    "The taste was pretty standard at {name}. Edible and warm, but lacked rich seasonings and punch.",
    "Mediocre flavors at {name}. The starters were alright, but the main course was fairly bland.",
    "Food quality was average at {name}. Good for a quick bite, but don't expect gourmet restaurant standards.",
    "Taste was strictly okay at {name}. Some dishes needed more salt and seasoning to bring out the flavors.",
    "Nothing exceptional about the food at {name}. Standard cafe fare that you can get almost anywhere.",
    "Average preparation at {name}. The pasta sauce was somewhat runny and the garlic bread was a bit dry.",
    "Decent food at {name}, but feels like the recipes could use more refinement and better spice balance.",
    "The food at {name} was neither memorable nor terrible. Just a middle-of-the-road dining experience."
  ,
    // 11-20: Price vs Value
    "Felt a bit overpriced for the portions served at {name}. Ambiance is nice, but food value was strictly average.",
    "A bit steep on the pocket for what is offered at {name}. Taste was fine, but portions were quite small.",
    "The ambiance justifies some of the pricing at {name}, but the food quality needs to step up to match the bill.",
    "Average value for money at {name}. You pay mostly for the aesthetic decor rather than extraordinary taste.",
    "Portion sizes at {name} could be slightly bigger considering the prices charged on the menu.",
    "Expensive for standard cafe items at {name}. Good place to click photos, but food value is just 3 stars.",
    "The bill felt a bit high compared to our satisfaction level at {name}. Average food for premium pricing.",
    "Decent spot, but {name} charges a premium that isn't fully reflected in the culinary execution.",
    "Value was fair, but could be better at {name}. The sandwiches and fries were quite ordinary for the price.",
    "Pricing is on the higher side at {name}, while the taste remains strictly in the average territory."
  ,
    // 21-30: Service Delays
    "The service at {name} was quite sluggish today. We had to wait almost 35 minutes for our first dish.",
    "Decent food, but slow service at {name}. The staff seemed a bit scattered and took time to bring our bill.",
    "Waited quite a while for our coffee and snacks at {name}. Service speed needs noticeable improvement.",
    "The staff was polite, but service at {name} was slow. Drinks arrived long before the starters were ready.",
    "Speed of service at {name} could definitely be better. Long gaps between ordering and receiving the food.",
    "Service was delayed despite the cafe not being completely packed. {name} needs better kitchen coordination.",
    "Had to follow up twice on our order at {name}. Staff was nice, but turnaround time was below expectations.",
    "Took a long time to get our food at {name}. Good ambiance helped pass the time, but service was slow.",
    "The waiting time tested our patience at {name}. Once the food arrived it was fine, but the delay was noticeable.",
    "Average service efficiency at {name}. Took 20 minutes just to get a bottle of water and menu cards."
  ,
    // 31-40: Mixed Bag Dishes
    "A mixed experience at {name}. The pizza was enjoyable, but the pasta was quite underwhelming and bland.",
    "Some hits and some misses at {name}. Loved the cold coffee, but the burger patty was dry and overcooked.",
    "Inconsistent quality at {name}. Starters were fresh and crispy, while the main course felt under-seasoned.",
    "One dish was good while the other was mediocre at {name}. Hope the kitchen achieves more consistency.",
    "The beverage was flavorful, but the snacks at {name} were oily and lacked crispness. 3 stars overall.",
    "Half of our order at {name} was good, the other half fell flat. A 50-50 experience across our table.",
    "The fries were great, but the sandwich filling at {name} was minimal. A mixed culinary bag today.",
    "Liked the dessert at {name}, but the savory dishes were just passable. Needs more balanced execution.",
    "Drinks were well-made at {name}, but the food needs substantial improvement to match up. Average visit.",
    "Some items tasted fresh while others felt reheated at {name}. Quality consistency is clearly needed."
  ,
    // 41-50: Noise & Crowding
    "Very loud music at {name}. Hard to have a normal conversation without having to raise your voice.",
    "The cafe was very noisy during our visit to {name}. Seating was close together, feeling slightly cramped.",
    "Decor is nice at {name}, but the background noise level made it difficult to relax or chat comfortably.",
    "A bit too chaotic during evening hours at {name}. Staff was rushing around and music was blasting.",
    "The acoustics at {name} amplify the chatter. It was difficult to hear each other across the table.",
    "Seating density is high at {name}. Tables are placed very close to one another, reducing privacy.",
    "Energetic vibe at {name}, but too noisy for a relaxed evening. Good for parties, not great for casual conversations.",
    "Music was so loud at {name} that we had to repeat our order three times to the server. An okay visit.",
    "The crowd was large and the cafe felt slightly overwhelmed. {name} needs better crowd control.",
    "Loud atmosphere at {name}. If you're looking for a peaceful cafe, this might not be the best pick."
  ,
    // 51-60: Ordinary Hospitality
    "The staff at {name} was strictly neutral. No greeting, no follow-up, just did the bare minimum required.",
    "Hospitality was just okay at {name}. The staff didn't seem particularly enthusiastic or attentive.",
    "Service felt mechanical at {name}. Waiters took orders and dropped plates without much warmth or courtesy.",
    "Staff at {name} was neither rude nor friendly. A very indifferent service experience throughout the meal.",
    "Could use better hospitality training for the floor staff at {name}. Lacked attention to customer comfort.",
    "Nobody checked if our food was fine or if we needed anything else at {name}. Basic service standards.",
    "The staff was busy chatting among themselves near the counter at {name} while customers were waiting.",
    "Indifferent service at {name}. Had to stand up and walk to the counter to ask for tissue papers and napkins.",
    "Hospitality was lackluster at {name}. A warmer approach from the crew would make a big difference.",
    "Basic service at {name}. Nobody seemed particularly interested in ensuring a memorable dining experience."
  ,
    // 61-70: Menu Availability & Options
    "Several popular items on the menu were unavailable during our visit to {name}. Limited our choices.",
    "Disappointed that two of the signature dishes we wanted to try were out of stock at {name}.",
    "The menu has many items listed, but {name} had multiple exclusions today. Ended up settling for second choices.",
    "Limited vegetarian selections available today at {name}. The available items were okay, but choices felt restricted.",
    "Out of ice and fresh mint when we ordered mocktails at {name}. Had to switch drinks halfway through.",
    "A few key ingredients were missing at {name}, so our preferred dishes could not be made. Fairly average.",
    "Menu variety looked promising, but {name} was out of basic supplies on a regular weekday afternoon.",
    "Stock management at {name} needs work. Had to re-order twice because kitchen ran out of ingredients.",
    "Limited dessert options were available at {name}. Only one brownie flavor left by 7 PM.",
    "Menu execution was restricted due to missing items at {name}. What we got was edible, but not what we wanted."
  ,
    // 71-80: Temperature & Freshness
    "Food arrived barely warm at {name}. The cheese had already hardened by the time the pizza reached our table.",
    "The soup was lukewarm and had to be sent back for reheating at {name}. Decent taste once heated, though.",
    "My coffee arrived warm rather than hot at {name}. Tasted fine, but expected freshly brewed piping hot coffee.",
    "The bread served at {name} was slightly stale and crumbly. Rest of the dish was okay, but freshness was lacking.",
    "Fries were limp and not as crispy as expected at {name}. Seemed like they were fried in advance.",
    "Food temperature was an issue at {name}. Mains were served before starters were cleared and cooled down quickly.",
    "Appetizers at {name} felt like they were sitting on the counter for a while before being brought out.",
    "The beverage was not chilled enough at {name}. Had to request extra ice cubes to make it refreshing.",
    "Pastry was slightly dry around the edges at {name}. Clearly wasn't baked fresh that same morning.",
    "Decent recipes at {name}, but lukewarm serving temperatures detracted from the overall eating experience."
  ,
    // 81-90: Hygiene & Upkeep
    "The table was slightly sticky when we sat down at {name}. Had to ask the server to wipe it down again.",
    "Cutlery at {name} had water spots and wasn't polished properly. Basic hygiene needs more strict vigilance.",
    "Cleanliness was average at {name}. Crumbs on the seat from previous guests were not brushed off promptly.",
    "The washroom at {name} was in need of maintenance and cleaning. A cafe of this stature should keep it spotless.",
    "Napkin dispensers were empty at our table in {name}. Table setup felt somewhat hurried and careless.",
    "Spotted dirty plates sitting on neighboring tables for over 25 minutes at {name}. Needs faster clearing.",
    "Overall cleanliness at {name} was passable, but certainly not pristine. Hand sanitizers were empty too.",
    "Floor had visible tissue litter in the corner at {name}. Staff should do routine walkthroughs to keep it tidy.",
    "Menu cards at {name} were stained and torn. A fresh set of menus would give a much better impression.",
    "Passable upkeep at {name}, but small cleanliness lapses prevented this from being a higher-rated visit."
  ,
    // 91-100: Overall Mediocrity
    "Overall, {name} is an ordinary cafe. Nothing to complain heavily about, but nothing to rave about either.",
    "A completely middle-of-the-road experience at {name}. It's fine if you're nearby, but not worth a special trip.",
    "3 stars for {name}. Good aesthetics, but average food and mediocre service make it just another cafe.",
    "Had average expectations from {name}, and the visit met them without exceeding in any area.",
    "It's an okay spot to spend an hour, but {name} doesn't leave any lasting impression on your palate.",
    "Expected a little more based on reviews of {name}. Ended up being a standard, unremarkable outing.",
    "A fair, standard cafe experience at {name}. Adequate for a quick break, but has plenty of room to improve.",
    "Strictly 3 stars for {name}. Nice decor, but kitchen output and service speed need serious fine-tuning.",
    "It was fine. {name} has the looks, but the substance needs work to match the visual appeal.",
    "Ordinary dining at {name}. Not bad enough to avoid, but not compelling enough to rush back anytime soon."
  ],

  2: [
    // 1-10: Cold & Bland Food
    "Very disappointed with the food at {name}. Everything arrived cold, bland, and lacked any real seasoning.",
    "The food at {name} was nearly unpalatable. Soggy fries, tasteless pasta, and totally cold by the time it arrived.",
    "Expected much better from {name}. The pizza base was rubbery, the sauce was sour, and the toppings were dry.",
    "Food quality was well below average at {name}. Stale buns, cold burger patty, and completely missing sauces.",
    "The dishes at {name} were drowning in excessive oil and lacked flavor. We couldn't finish even half of our meal.",
    "Very poor food execution at {name}. Soup was watered down and the garlic bread was burnt to a crisp.",
    "Tasteless and overpriced! The chef at {name} clearly cut corners today. Deeply unsatisfied with the quality.",
    "Had high hopes for {name}, but the food was a letdown. Cold dishes, tough meat, and dry bread all around.",
    "The taste was substandard at {name}. Flavors felt artificial and the dishes arrived lukewarm at best.",
    "Extremely bland food at {name}. Had to ask for extra salt, pepper, and oregano just to make it edible."
  ,
    // 11-20: Unacceptable Waiting Times
    "Waited over 45 minutes for two simple beverages and a starter at {name}. Completely disorganized kitchen!",
    "Terrible waiting times at {name}! People who arrived after us were served before us. Very frustrating experience.",
    "We spent more time waiting for our food than actually eating at {name}. Over 50 minutes of delay!",
    "Kitchen management at {name} is a disaster. Took an eternity to get basic sandwiches onto our table.",
    "If you are hungry, stay away from {name}. The waiting time is excruciatingly long with zero updates from staff.",
    "Had to ask the server four times about our order status at {name}. Still took nearly an hour to arrive.",
    "The delay ruined our lunch at {name}. We had to rush through our meal because of how late the food arrived.",
    "Horrible pacing at {name}. One dish came in 20 minutes, the next one took another 40 minutes. Completely disjointed.",
    "Waited 30 minutes just for drinks at {name}! No apology or explanation offered by the manager.",
    "Extremely slow turnaround time at {name}. The kitchen was clearly understaffed and couldn't handle the orders."
  ,
    // 21-30: Inattentive & Neglectful Staff
    "Service at {name} was completely inattentive. We had to wave our hands repeatedly just to get the waiter's attention.",
    "Staff at {name} seemed completely disinterested in serving customers. Felt like we were bothering them.",
    "Very poor hospitality at {name}. The staff ignored our calls and walked past our table multiple times.",
    "Nobody attended to our table for 15 minutes after we were seated at {name}. Had to fetch menus ourselves.",
    "The attitude of the servers at {name} was cold and dismissive. Customer service is practically nonexistent.",
    "Servers at {name} lacked basic training. Kept forgetting items we ordered and brought the wrong drinks twice.",
    "Neglectful service at {name}. Waited 20 minutes after finishing our meal just to get someone to bring the bill.",
    "The staff at {name} showed zero care for guest satisfaction. Very unwelcoming and robotic behavior.",
    "Had a terrible experience with the staff at {name}. Inattentive, unresponsive, and unapologetic.",
    "Floor staff at {name} was completely disorganized. No dedicated servers and nobody taking accountability."
  ,
    // 31-40: Overpriced & Poor Value
    "Total waste of money at {name}! Charged exorbitant prices for tiny portions of subpar quality food.",
    "The prices at {name} are ridiculous compared to what is served. You pay for the decor, but get terrible food.",
    "Horrible value proposition at {name}. Heavy bill with almost zero culinary satisfaction. Not worth it.",
    "Overpriced and under-delivered. {name} charges fine-dining rates for substandard cafe food.",
    "The bill shocked us considering how bad the food was at {name}. Would never spend money here again.",
    "Way too expensive for such poor portions and average taste at {name}. A thoroughly disappointing outing.",
    "Felt ripped off at {name}. High prices, small portions, and dishes that tasted like pre-packaged frozen food.",
    "Value for money is zero at {name}. You leave with an empty stomach and a significantly lighter wallet.",
    "Inflated prices without the quality to back it up at {name}. Don't fall for the social media photos.",
    "Extremely poor cost-to-satisfaction ratio at {name}. Definitely not recommending this to anyone on a budget."
  ,
    // 41-50: Order Mix-ups & Careless Errors
    "The staff at {name} messed up our entire order. Brought non-veg instead of veg, which is completely unacceptable!",
    "Got the wrong order twice at {name}. By the time they corrected it, everyone else at the table had finished eating.",
    "Careless mistakes at {name}! Ordered no cheese due to allergies, but the dish came loaded with cheese.",
    "Two items we ordered never showed up at {name}, but they were still added to our bill! Check your invoices.",
    "Confusion in the kitchen at {name}. Brought drinks meant for another table and argued when we pointed it out.",
    "Our order was mixed up completely at {name}. Servers seemed confused about table numbers and dish names.",
    "Ordered cold coffee and received a hot latte at {name}. Replaced it after 20 minutes with a watered-down version.",
    "Gross negligence in taking orders at {name}. Had to repeat simple instructions three times and still got it wrong.",
    "Wrong billing and wrong dishes at {name}. The staff seemed totally clueless about the menu offerings.",
    "Incorrect dishes served and zero apology from the management at {name}. Very sloppy operation."
  ,
    // 51-60: Uncomfortable Environment & Noise
    "The air conditioning was not working properly at {name}. It was uncomfortably hot and stuffy inside.",
    "Extremely loud, screeching music at {name}. Asked twice to lower the volume, but our request was ignored.",
    "The seating at {name} was horribly uncomfortable. Wobbly tables, cramped chairs, and zero legroom.",
    "Unpleasant dining environment at {name}. Flies buzzing around the indoor area and smoke from the kitchen.",
    "Suffocating atmosphere at {name}. Poor ventilation left the entire cafe smelling like burnt cooking oil.",
    "The venue at {name} was chaotic and loud. Felt more like a crowded railway station than a relaxing cafe.",
    "Dim lighting to the point where we couldn't even see what we were eating at {name}. Very frustrating.",
    "Wobbly table caused our drinks to spill at {name}, and staff took ten minutes just to bring a mop.",
    "Noise levels were unbearable at {name}. Screaming patrons and loud speakers made it a headache-inducing meal.",
    "Poor climate control at {name}. Either freezing cold right under the AC vent or boiling hot elsewhere."
  ,
    // 61-70: Hygiene Concerns
    "Cleanliness at {name} was alarming. The table had sticky sauce residues and cutlery was visibly soiled.",
    "Found hair in our food at {name}! When pointed out, the server merely shrugged and took the plate away.",
    "Dirty glasses and spotted spoons at {name}. Had to ask for replacements twice. Basic hygiene is ignored.",
    "The washroom was filthy and smelled awful at {name}. Completely ruined our appetite for the meal.",
    "Dusty cushions and dirty floor corners at {name}. Clearly lacks proper daily cleaning and sanitation.",
    "Observed the staff at {name} handling food and ice with bare hands after touching money. Very concerning.",
    "Unwashed glasses served to our table at {name}. You could see lipstick marks from previous customers!",
    "Flies and fruit flies hovering around the pastry display at {name}. Very unhygienic presentation.",
    "The ketchup bottle at our table in {name} was crusty and expired. Disgusting lack of cleanliness.",
    "Severe hygiene shortcomings at {name}. If the front of house is this dirty, I worry about the kitchen."
  ,
    // 71-80: Bad Drinks & Coffee
    "The coffee at {name} was bitter, burnt, and tasted like it was brewed with stale beans. Undrinkable!",
    "Ordered two mocktails at {name} and both were just cheap artificial syrup mixed with flat soda. Awful.",
    "Watery, flavorless shakes at {name}. Charged premium prices for what tasted like milk mixed with tap water.",
    "The cold brew at {name} was sour and completely flat. Easily one of the worst coffees I've had in the city.",
    "Drinks arrived lukewarm with melted ice at {name}. Zero freshness and totally lacked proper presentation.",
    "The tea at {name} was over-steeped, bitter, and served in a stained ceramic mug. Very disappointing.",
    "Ordered their signature beverage at {name} and it tasted like cough syrup. Couldn't take more than two sips.",
    "The smoothie at {name} had ice crystals and separated within two minutes. Very poorly made.",
    "Burnt espresso shots ruined the latte at {name}. Barista needs proper training on machine calibration.",
    "Flat soda and stale mint leaves ruined our drinks at {name}. Threw away half the glass."
  ,
    // 81-90: Poor Management
    "Spoke to the manager at {name} regarding our issues, and was met with arrogance and defensiveness.",
    "Management at {name} takes zero accountability. Blamed the kitchen staff in front of us rather than fixing the issue.",
    "Total lack of professionalism from the managerial team at {name}. They seemed unbothered by customer feedback.",
    "No supervisor on the floor at {name}. Junior staff had no guidance and chaos was visible everywhere.",
    "When we complained about cold food at {name}, the manager argued that this is how the dish is supposed to taste!",
    "Poor leadership at {name} reflects in the chaotic service and substandard food quality. Needs serious intervention.",
    "The floor manager at {name} showed zero empathy or problem-solving skills. Disappointing customer handling.",
    "Management at {name} only caters to VIPs or their friends. Regular walk-in guests are completely neglected.",
    "Arrogant management at {name}. A simple apology would have sufficed, but instead they gave defensive excuses.",
    "Total management failure at {name}. Disorganized seating, lost orders, and uncaring managerial attitude."
  ,
    // 91-100: Regret & Negative Recommendation
    "Deeply regret choosing {name} for our evening out. It was a stressful, unsatisfying experience from start to finish.",
    "Would not recommend {name} to anyone. There are far better cafes nearby that offer genuine quality and care.",
    "Save your money and go elsewhere! {name} relies solely on fake hype while delivering 2-star food and service.",
    "Huge disappointment at {name}. The reality is light years away from what is shown on their social media page.",
    "Won't be returning to {name}. Too many flaws in food, speed, hygiene, and service to ever justify coming back.",
    "2 stars only for the interior design, because everything else at {name} was thoroughly disappointing.",
    "Left {name} with a sour taste in our mouths and an empty stomach. A complete letdown of an outing.",
    "Don't waste your time or hard-earned money at {name}. Too many operational issues and subpar food.",
    "One of the most disappointing cafe experiences this year at {name}. Needs massive improvements across the board.",
    "Avoid {name} if you value good food, prompt service, or respectful treatment. Very underwhelming."
  ],

  1: [
    // 1-10: Extremely Rude Staff & Hostility
    "Horrendous experience at {name}! The staff was shockingly rude, argumentative, and behaved with total disrespect.",
    "Never been treated so poorly at a cafe! The waiter at {name} literally rolled his eyes and threw the bill on our table.",
    "Abysmal behavior from the staff at {name}! Extremely hostile and uncouth attitude towards paying customers.",
    "The manager at {name} was obnoxious and arrogant when we pointed out a genuine problem. Zero hospitality sense!",
    "Staff at {name} displayed utter contempt for customers. We were insulted for asking to change a dirty glass!",
    "Disgraceful service at {name}. Staff was yelling across the hall and treated our family with shocking rudeness.",
    "The level of disrespect from the staff at {name} was appalling. Will never step foot into this place again.",
    "Extremely arrogant management and staff at {name}. Treated us like they were doing us a favor by serving us.",
    "The staff at {name} ruined our day with their toxic attitude. A cafe that treats patrons like this should be shut down.",
    "Rude, hostile, and utterly unprofessional. The team at {name} has no business working in the hospitality sector."
  ,
    // 11-20: Rotten, Stale & Inedible Food
    "The food served at {name} was rotten and smelled awful! Had to spit it out immediately. Disgusting and dangerous!",
    "Suffered from severe food poisoning after dining at {name}! Stale ingredients, foul-tasting meat, and rancid oil.",
    "Inedible food! The chicken at {name} was completely raw inside while the outside was burnt. Hazardous to health!",
    "Food quality at {name} is pathetic. Tasted like leftovers that were repeatedly reheated over several days.",
    "The cheese was sour and expired on the pizza at {name}. Absolute health hazard! Avoid eating here at all costs.",
    "Disgusting food quality at {name}. Sour dairy, stale bread, and unwashed vegetables. Couldn't eat a single bite.",
    "Food smelled rotten at {name}. When we told the manager, he was rude and insisted on charging us anyway!",
    "Completely spoiled food served at {name}. Rancid smell coming from the gravy. Truly stomach-turning experience.",
    "The worst food I have ever been served in my entire life was at {name}. Stale, cold, and utterly repulsive.",
    "Zero hygiene in the kitchen at {name}! Rotten ingredients, stale sauces, and completely unsafe food."
  ,
    // 21-30: Gross Hygiene & Foreign Objects
    "Found an insect inside my drink at {name}! Absolutely revolting! Zero standards of hygiene and pest control.",
    "There was a dead fly inside our soup at {name}! The staff didn't even apologize, just took the bowl away.",
    "Cockroaches spotted crawling on the wall next to our dining table at {name}! Beyond disgusting and unacceptable.",
    "Found a strand of metal wire in the food at {name}! Could have caused serious medical injury. Shockingly careless!",
    "Stray pests inside the dining area and filthy kitchen conditions visible at {name}. Absolute health hazard!",
    "The glasses and plates at {name} had dried food remnants from previous diners. Pure filth and unhygienic neglect.",
    "Found plastic packaging melted inside our baked pasta at {name}! Unbelievably reckless kitchen standards.",
    "The dining area at {name} smelled like an open sewer. Filthy floors, stained tables, and zero sanitation.",
    "Hair in the starter and insect in the main course at {name}! Two contaminated dishes in one meal. Horrific!",
    "Extremely unhygienic! The kitchen at {name} looks like a disaster zone. Food safety authorities must inspect this."
  ,
    // 31-40: Extreme Delays & Abandonment
    "Waited 1 hour and 15 minutes at {name} and food NEVER arrived! We had to walk out hungry and furious.",
    "Complete disaster at {name}! They lost our order slip, made us wait 70 minutes, and then admitted they forgot!",
    "Ordered two coffees and waited over 50 minutes at {name}. Nobody cared, nobody checked, zero service!",
    "We were totally abandoned at our table in {name}. Over an hour wait with empty glasses and zero updates.",
    "Walked out of {name} after waiting 80 minutes without getting a single dish! Worst cafe management ever seen.",
    "Kitchen forgot about our table completely at {name}. When we asked after an hour, they asked us to re-order!",
    "Excruciating 90-minute delay at {name}! Left the venue famished and thoroughly aggravated. Total failure.",
    "Took over an hour for basic french fries and a soda at {name}. Absolute mockery of customer service.",
    "Kept telling us '5 more minutes' for over an hour at {name}. Total dishonesty and pathetic coordination.",
    "Waited forever at {name} while the staff stood around doing nothing. Walked out without eating. Horrible place!"
  ,
    // 41-50: Overcharging, Fraud & Billing Scams
    "Complete scam at {name}! Added extra items to our bill that we never ordered and refused to remove them.",
    "Check your bills carefully at {name}! They overcharge on taxes, sneak in extra charges, and argue aggressively.",
    "Charged us for premium bottled water when they actually served regular tap water at {name}! Unethical scam!",
    "Billing fraud at {name}! Prices on the printed invoice were 30% higher than the menu prices shown to us.",
    "Disputed an unauthorized surcharge at {name} and the cashier threatened and misbehaved with us. Shocking!",
    "Charged us twice for the same dish on the credit card machine at {name} and refused to process a refund.",
    "Hidden fees, mandatory tips forced on customers, and bogus service charges at {name}. Complete daylight robbery!",
    "The cashier at {name} was blatantly dishonest. Tried to pocket the change and argued when called out.",
    "Overpriced menu followed by fraudulent billing items at {name}. Completely unethical business practices!",
    "They charged us for dishes that were sent back untouched due to being spoiled at {name}. Shameless greed!"
  ,
    // 51-60: Ruined Celebrations & Special Days
    "{name} completely ruined our anniversary celebration! Terrible food, rude staff, and chaotic service. Devastated.",
    "Booked a table for my daughter's birthday at {name} and they gave our table away to someone else! Heartbreaking.",
    "Our family gathering was turned into a nightmare by the incompetent staff at {name}. Ruined our special day.",
    "Planned a special dinner at {name} and it turned into the most embarrassing, frustrating night of the year.",
    "Celebrated a major milestone at {name} and was met with raw food, delayed service, and rude managers. Ruined!",
    "Total catastrophe! {name} ruined our family reunion. Cold food, dirty tables, and an argumentative manager.",
    "Do NOT plan any celebration at {name}! They will ruin your mood, your party, and your memories completely.",
    "Worst birthday dinner ever at {name}! Waited an hour, got incorrect orders, and staff was completely unapologetic.",
    "Brought out-of-town guests to {name} and was thoroughly embarrassed by the abysmal quality and service.",
    "Our evening was completely wrecked by the staff and kitchen at {name}. Unforgivable lack of competence!"
  ,
    // 61-70: Total Chaos & Kitchen Meltdown
    "Absolute circus at {name}! Waiters dropping plates, kitchen shouting, wrong tables served, pure pandemonium.",
    "Total breakdown of operations at {name}. Staff running around headless while food sits rotting on counters.",
    "The kitchen at {name} is in complete chaos. Orders mixed up, food coming out cold, and staff yelling at each other.",
    "Never seen such unprofessionalism! The staff at {name} were having loud arguments in front of paying guests.",
    "Uncontrollable chaos at {name}. Waited 40 minutes only to be told they lost our order ticket. Incompetence peak!",
    "Zero management oversight at {name}. Customers shouting, tables uncleared, and kitchen completely backed up.",
    "A total logistical disaster! {name} accepts more guests than they can handle and everything crashes down.",
    "Disorganized, noisy, and chaotic beyond words at {name}. Nobody knows who is cooking or who is serving.",
    "Sloppy, reckless, and dysfunctional operation at {name}. One of the worst run establishments in the city.",
    "Total mismanagement at {name}! If you want peace and proper food, this place is the exact opposite."
  ,
    // 71-80: Toxic Environment & Safety
    "Felt completely unsafe and unwelcome at {name}. Unruly crowd, no security, and staff did nothing to intervene.",
    "The venue at {name} was smoky, suffocating, and hazardous. Zero air ventilation or fire safety visible.",
    "Bouncers and staff at {name} behaved aggressively with patrons. Terrible, toxic atmosphere!",
    "Unsafe and hazardous setup at {name}. Wires dangling near tables and broken tiles on the walkway. Avoid!",
    "Aggressive behavior from the security and staff at {name}. Threatening attitude towards regular customers.",
    "Zero crowd management or safety measures at {name}. Crammed so many people inside that exits were blocked.",
    "Very shady and uncomfortable environment at {name}. Would never recommend families or women to visit.",
    "Staff at {name} encouraged an unruly group creating nuisance instead of maintaining decorum. Dreadful.",
    "Poor lighting, slippery wet floors with no warning signs, and zero care for guest safety at {name}.",
    "Hostile, aggressive, and toxic atmosphere at {name}. One of the worst dining experiences imaginable."
  ,
    // 81-90: Absolute Disgust & Stomach Illness
    "Got severe food poisoning within hours of eating at {name}. Spent two days in bed with stomach cramps. Toxic!",
    "My entire family fell sick after eating the pasta and pizza at {name}! Pure poison being served in the name of food.",
    "The food at {name} was stale, rancid, and gave me acute gastroenteritis. AVOID AT ALL COSTS!",
    "Terrible stomach infection after visiting {name}. The dairy products were clearly spoiled and foul. Disgraceful!",
    "Fell violently ill after dining at {name}. Never felt so sick from restaurant food in my life. Never again!",
    "Stomach flu caused by the contaminated food and water at {name}. Total negligence towards health safety.",
    "Woke up with severe nausea and fever after eating at {name}. Inexcusable lack of hygiene and food quality.",
    "Medical nightmare after visiting {name}. Doctor confirmed bacterial food contamination from undercooked food.",
    "Poisonous food being served at {name}! Stale, infected, and completely unhygienic. Health authorities take note!",
    "Both my friend and I developed food poisoning from {name}'s starters. Pathetic and unforgivable standards."
  ,
    // 91-100: Definitive 1-Star Verdicts
    "Zero stars if I could! {name} is by far the worst cafe experience in existence. Stay as far away as possible!",
    "Do NOT visit {name}! Total waste of money, terrible food, rude staff, and complete disrespect for guests.",
    "A complete nightmare from beginning to end! {name} fails on food, fails on hygiene, and fails on service.",
    "Save yourself the headache, money, and stomach ache. Avoid {name} like the plague! Absolute disaster.",
    "I would give minus stars to {name} if Google allowed it. Utterly appalling and pathetic establishment.",
    "Never coming back, never recommending. {name} is the gold standard for how NOT to run a restaurant.",
    "The worst dining decision of my life was walking into {name}. Pathetic food, filthy place, and rude staff.",
    "Warning to everyone: Avoid {name}! Overpriced garbage food, hostile management, and filthy premises.",
    "A catastrophic failure in every possible way. {name} does not deserve a single customer. Disgraceful!",
    "Worst cafe in the entire city! {name} is a complete fraud. Save your hard-earned money and eat elsewhere."
  ]
}
